### ISSUE TITLE
Permission to use API in a CLI project

### ISSUE THREAD

**Issue by gamtiq** [webcomponents/webcomponents.org#1013]
According to the following note from [API page](https://github.com/webcomponents/webcomponents.org/blob/master/API.md):
> Before using the API, please file an issue with your intention of using the API.

I would like to ask your permission to use the API in my project [seeq](https://github.com/gamtiq/seeq). Is it possible?

**Comment by samuelli** [comment]
Of course!

The issue is so we can keep track of who's using the API in case we need to make changes (since we don't have any robust API process right now).

Thanks for letting us know.
