### ISSUE TITLE
Demos not loading after recent update

### ISSUE THREAD

**Issue by wchargin** [webcomponents/webcomponents.org#1018]
About fifteen minutes ago, I had the [`paper-toast` demo][demo] open. I was notified that a new version was available and to refresh. Upon refreshing, the demo does not work. Demos for other `paper-*` components do not work, either.

The symptom is that the demo page renders only, "undefined is not a valid dependency for v2.0.0 in polymerelements/paper-button", where sometimes "v2.0.0" is replaced by "v2.0.1" or "v2.0.2."

examples:
  - https://www.webcomponents.org/element/PolymerElements/paper-button/demo/demo/index.html
  - https://www.webcomponents.org/element/PolymerElements/paper-input/demo/demo/index.html
  - https://www.webcomponents.org/element/PolymerElements/paper-slider/demo/demo/index.html
  - https://www.webcomponents.org/element/PolymerElements/paper-toast/demo/demo/index.html

There is 404 on `https://raw-dot-custom-elements.appspot.com/PolymerElements/paper-button/v2.0.0/undefined/demo/index.html`, but there are no other console errors.

Tested Chrome and Firefox on clean caches (by which I mean incognito and Ctrl-Shift-R).

[demo]: https://www.webcomponents.org/element/PolymerElements/paper-toast

**Comment by samuelli** [comment]
Thanks for reporting! Should be fixed now.

**Comment by wchargin** [comment]
Thank you! It is fixed after a cache-cleared refresh.
