### ISSUE TITLE
License doesn't refresh if changed

### ISSUE THREAD

**Issue by btopro** [webcomponents/webcomponents.org#1023]
Noticed that after changing the license on github for an element registered to webcomponents site it doesn't change to reflect. Is there a way to trigger a cache rebuild of an element or to check this after registering? It's not super common to change licenses but it would be good if they were in sync.

**Comment by samuelli** [comment]
Hi @btopro,

Do you have a link for the repo and what the license was changed from/to?

Thanks.

**Comment by btopro** [comment]
yup, any and all LRNWebComponents elements that say GPLv3. They are supposed to be Apache2 -- https://github.com/LRNWebComponents/lrndesign-paperstack/tree/0.0.3

https://www.webcomponents.org/element/LRNWebComponents/lrndesign-paperstack as one such example
