### ISSUE TITLE
webcomponents.org broken in IE11

### ISSUE THREAD

**Issue by mdwragg** [webcomponents/webcomponents.org#1027]
Hi,

Sadly the site seems to be not working in IE11... Going to the top of the site and clicking on 'Browse Elements' just gives me an empty page. No errors in the console.

Thanks,
Martin.

**Comment by arthurevans** [comment]
I believe this is the result of upgrading the the hybrid iron-ajax (2.0.0) which requires a promise polyfill on IE. The polyfill was included in iron-ajax 1.x, and is included in the webcomponents v1 polyfill. Running iron-ajax 2.0.0 with Polymer 1.x, you need the polyfill.

**Comment by arthurevans** [comment]
@samuelli FYI ^^

**Comment by arthurevans** [comment]
Related fix on docs site: https://github.com/Polymer/docs/pull/2272/files

**Comment by araker** [comment]
I'm also browsing with ie 11 and get the error message 'Promise is not defined'.

**Comment by mdwragg** [comment]
👍 Thanks!
