### ISSUE TITLE
New release isn't picked up

### ISSUE THREAD

**Issue by ronnyroeller** [webcomponents/webcomponents.org#1028]
We created 20h ago (2017-07-07T22:44:18Z) a new [2.1.1. release](https://github.com/Collaborne/candy-progress/releases) of the candy-bar element.

The [webcomponents.org page](https://www.webcomponents.org/element/Collaborne/candy-progress) still shows the old 2.0.3 release.

**Comment by kelvinwatson** [comment]
I am also seeing this issue on my [component](https://www.webcomponents.org/element/watsonlogic-software/watsonlogic-parallax). I've tagged release on my [repo](https://github.com/watsonlogic-software/watsonlogic-parallax/releases) but they have not been picked up.

**Comment by samuelli** [comment]
Apologies! There was a bug in an earlier PR, which was causing the queue to be blocked, preventing updates to come through. This has been fixed and the queue has been flushed, so you should be seeing up to date content now.
