### ISSUE TITLE
The Github pull request webhook doesn't work

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#1029]
In the GitHub repository settings:

<img width="1005" alt="screen shot 2017-07-10 at 16 14 31" src="https://user-images.githubusercontent.com/1007051/28022242-e4b9d756-658a-11e7-8763-c47b581df8b9.png">

The PR:

https://github.com/abdonrd/device-orientation/pull/11

<hr>

[Origin page](https://www.webcomponents.org/element/abdonrd/device-orientation)

**Comment by samuelli** [comment]
Hmm, I repro'd the same issue on my repo, but removing the webhook and re-adding it fixed the issue for me, so I'm not sure what's going on.

**Comment by abdonrd** [comment]
@samuelli ok, I will try now!

**Comment by abdonrd** [comment]
@samuelli btw, a redirect would be nice:

<img width="500" alt="screen shot 2017-07-10 at 21 00 15" src="https://user-images.githubusercontent.com/1007051/28034930-0183e552-65b3-11e7-9e95-3cde7f875cfc.png">

**Comment by abdonrd** [comment]
Closing and old issue.
