### ISSUE TITLE
paper-input incompatible with Microsoft Edge browser

### ISSUE THREAD

**Issue by eduardopthiago** [webcomponents/webcomponents.org#1034]
[Origin page](https://www.webcomponents.org/element/PolymerElements/paper-input)

paper-input is not working correctly on Microsoft Edge. 
![paper-input error edge](https://user-images.githubusercontent.com/4075146/28319307-e2f26d60-6ba3-11e7-9f2f-ee5e8e53fd27.PNG)

Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by samuelli** [comment]
Closing this issue as unrelated to webcomponents.org itself.
