### ISSUE TITLE
Update element / scratch-card

### ISSUE THREAD

**Issue by SaifJerbi** [webcomponents/webcomponents.org#1044]
I updated my scratch-card component on github, i updated the README.md file. It works well when i'm in [github](https://github.com/SaifJerbi/scratch-card/blob/v1.0.0/README.md). But when i'm in [webcomponent.org](https://www.webcomponents.org/element/SaifJerbi/scratch-card) site, it display "empty readme file"

**Comment by samuelli** [comment]
It looks fine to me? Maybe you were looking at a cached version.

![image](https://user-images.githubusercontent.com/787668/28933628-a23880fc-7832-11e7-93aa-e4c79a78cdc8.png)

**Comment by SaifJerbi** [comment]
I cleared the cache but the problem persist. So i created a new version (v1.0.1) it works fine. 
If you switch to v1.0.0 you will get this screen: 

![screenshot from 2017-08-04 09-13-05](https://user-images.githubusercontent.com/3641677/28960158-d4f52272-78fd-11e7-8a48-0f7020d00a9d.png)

**Comment by samuelli** [comment]
It looks like the tag was modified at some point. v1.0.0 was pointing to this commit: https://github.com/SaifJerbi/scratch-card/commits/2e5725dafea0565aad9f75e2b6e58b3f52752a64

Versions based on semver should never be modified and instead the numbers should be bumped every time there is a change.

**Comment by SaifJerbi** [comment]
Yeah I think it was a mistake. I close the issue. Thanks for your help
