### ISSUE TITLE
Empty results page is empty

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/webcomponents.org#1050]
[Origin page](https://www.webcomponents.org/search/asfasdfasdf)

Doesn't say anything about there not being any results.

**Comment by Link2Twenty** [comment]
If should be fairly straightforward to catch a zero result case. The real question is what should it say when there are zero results.

Adding these bits to [catalog-list](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-list.html) will display a simple message

```html
<template is="dom-if" if="[[_zeroResults]]">
  <h1 class="section-header">Oh snap, zero results!</h1>
</template>
```

```js
_zeroResults: function() {
  return (this._elements.count + this._collections.count <= 0);
},
```

**Comment by samuelli** [comment]
Maybe the title just changes. Instead of `Results for "asfasdfasdf"` it says `No results for "asfasdfasdf"`. "Oh snap" implies that it might be an error. What do you think?

**Comment by Link2Twenty** [comment]
Agreed, it ought to not sound like an error.

The [material design spec](https://material.io/guidelines/patterns/empty-states.html) has some suggestions for empty states. If I remember correctly customelements.io had the heading Zero results for "asfasdfasdf" then a [magnifying glass with a sad face](https://github.com/customelements/www/blob/master/assets/images/404.svg) below that.

**Comment by samuelli** [comment]
Anything simple is fine here :). Not a huge UX issue.

**Comment by Link2Twenty** [comment]
In order to change that header, we'd have to get the total results to bubble up to [catalog-search](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-search.html).

How about something like.

**catalog-list**
```JS
totalResults: {
  type: Number,
  computed: '_add(_elements.count, _collections.count)'
},
```

```JS
_add: function(a, b) {
  return a + b;
},
```

**catalog-search:**

```HTML
<catalog-list id="list" totalResults="[[totalResults]]" query="[[query]]" base-urls="[[baseUrls]]" loading="{{loading}}" disabled="[[!visible]]"></catalog-list>
```

```JS
_title: function(query, title) {
  if(!this.totalResults)
    return `No results for "${query}"`;
  // If we wanted we could just have 0 results for ... rather than No results either works.
  return title ? title : `${this.totalResults} results for "${query}"`;
},
```
