### ISSUE TITLE
Trouble publishing custom element

### ISSUE THREAD

**Issue by paales** [webcomponents/webcomponents.org#1051]
I'm publishing an element on webcomponents.org, but I'm having trouble getting the `<element>` tabs to show on the page:

https://www.webcomponents.org/element/reach-digital/polymer-apollo-client
https://github.com/reach-digital/polymer-apollo-client

I'd expect to have three additional tabs: <graphql-client>, <graphql-query> and <graphql-mutation> all with additional demo page.
Ideas?

**Comment by samuelli** [comment]
Hi,

Inside your bower.json, your main field should be point to a file which includes all the elements in your repository. See some other elements on how they do this.

**Comment by paales** [comment]
That did the trick! Thanks
