### ISSUE TITLE
Component Life Cycle differs between DOM inserted and `document.createElement`

### ISSUE THREAD

**Issue by intervalia** [webcomponents/webcomponents.org#1063]
So there seems to be a bug, in Chrome, in the manual creation of a Web Component that has a sub-Web Component in its template. When I do `var x = document.createElement('outer-el')` the `constructor` for the `outer-el` is called but the `constructor` for the `inner-el` is not called until AFTER the outer `connectedCallback` is called.

Template for `outer-el`
```
<template>
  <div>
    <inner-el></inner-el>
  </div>
</template>
```

When I call `var a = document.createElement('outer-el')` then the `constructor` for `outer-el` is called. But not the `constructor` for the `inner-el`

When I call `document.body.appendChild(a)` then the `connectedCallback` for the `outer-el` is called.

Then, after the outer `connectedCallback` is the inner `constructor` and `connectedCallback` called.

Here is what happens:
```
> var a = document.CreateElement('outer-el');
// outer-el `constructor` called

> document.body.appendChild(a);
// outer-el `connectedCallback` called
// inner-el `constructor` called
// inner-el `connectedCallback` called
```

Now if I include the `outer-el` in the DOM of the page then this happens:

```
// outer-el `constructor` called
// inner-el `constructor` called
// inner-el `connectedCallback` called
// outer-el `connectedCallback` called
```

This is what I would expect to happen, but it you create it manually then things are horked and your outer `constructor` can't access the inner element. Neither can the outer `connectedCallback`.

I have only tested this in Mac Chrome Version 61.0.3163.79 (Official Build) (64-bit) so far.

I realize this is probably because there is no mutation observer on an element that is not in the DOM, but this feels like a HUGE bug. If I understand how Web Component instantiation works then the sub element can't be created until the outer element is inserted into the DOM.

Anyone else run into this?

**Comment by arthurevans** [comment]
Is this a Polymer element? Or if not, are you inserting that template manually, or are you using a library?

**Comment by intervalia** [comment]
This is a native V1 component.
In the successful example I am just placing the `<outer-el></outer-el>` in the DOM.

In the failing example I am calling `document.createElement('outer-el')`.

The problem seems to be that there is a mutationObserver on body that catches when things are inserted directly into the DOM through `innerHTML` or when the page is first loaded. And that mutationObserver does this correctly.

But calling `createElement` does not seem to check the children to see if they are custom elements. That only happens when the element is added to the DOM through the `appendChild` call.

**Comment by intervalia** [comment]
Here is an example of the code:

```html
<link rel="import" href="layer-sub.html" />
<template>
<style data-type="layer-outer">
.shell {
  background-color: #0FF;
}
</style>
<div class="shell">
  <p>This is the outer element</p>
  <layer-sub inner="show me there"></layer-sub>
</div>
</template>
<script>
console.log('layer-outer.html loaded');
(function() {

  // Get the `<link>`, `<style>` and the DOM template
  var frag = (document.currentScript||document._currentScript).ownerDocument.querySelector('template').content;
  var _styles = frag.children[0];
  var _template = frag.children[1];

  // Class for `<layer-outer>`
  class layerOuter extends HTMLElement {
    constructor() {
      super();
      console.log(`layerOuter[${this.id}] constructor`);
      var sd = this.attachShadow({mode: 'closed'});
      sd.appendChild(_styles.cloneNode(true));
      sd.appendChild(_template.cloneNode(true));
    }

    connectedCallback() {
      console.log(`layerOuter[${this.id}] connectedCallback`);
    }

    disconnectedCallback() {
      console.log(`layerOuter[${this.id}] disconnectedCallback`);
    }
  }

  // Define our web component
  customElements.define('layer-outer', layerOuter);
})();
</script>
```

**Comment by intervalia** [comment]
And the HTML file that loads the outer element:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Component and Subcomponet</title>
    <link rel="import" href="layer-outer.html" />
  </head>
  <body>
    <layer-outer id="first"></layer-outer>
    <hr/>
    <layer-outer id="second" inner="tacos are great"></layer-outer>
  </body>
</html>
```

**Comment by intervalia** [comment]
And this is the console output I get:

```
layerOuter2[first]  constructor
--------Sub[]       constructor
--------Sub[]       connectedCallback
layerOuter2[first]  connectedCallback
layerOuter2[second] constructor
--------Sub[]       constructor
--------Sub[]       connectedCallback
layerOuter2[second] connectedCallback
```

**Comment by intervalia** [comment]
Then, when I try to manually create one through dev tools I see the following:

```
> a = document.createElement('layer-outer')

layerOuter[]       constructor


> document.body.appendChild(a)

layerOuter[]       connectedCallback
------ Sub[-inner] constructor
------ Sub[-inner] connectedCallback
```

As you can see, the inner `constructor` does not get called until after I add the outer element into the DOM. But, for consistency sake, the inner element should have been created when the outer element was created. The instant that I appended the template into the outer element's shadowDom I would have expected the inner `constructor` and `connectedCallback` function to be called.

**Comment by arthurevans** [comment]
Ah, right. I see. I think the issue has to do with the way custom elements are upgraded:

https://w3c.github.io/webcomponents/spec/custom/#custom-elements-upgrades-examples

In particular, "Note that upgrades only apply to elements in the document tree. (Formally, elements that are connected.) An element that is not inserted into a document will stay un-upgraded. ..."

In this case, I _think_ when you call `document.createElement`, you get an upgraded element back from the browser. But the elements created by the clone node don't get upgraded. Since the parent isn't connected, they aren't associated with a custom element registry and they don't get upgraded until the parent is attached.

I am, however, on very shaky ground here, so I'll defer to @bicknellr, @justinfagnani or @azakus who can perhaps clarify if this behavior sounds correct? If this isn't WAI, we should probably raise a chrome bug.

**Comment by intervalia** [comment]
I now see the limit. I think it is a bug, but I see it. It would be nice if we could change `document.createElement` to include a argument to tell it to auto-upgrade the children instead of waiting until it gets into the DOM.
