### ISSUE TITLE
audio/video from demo page keeps playing after closing the demo dialog

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/webcomponents.org#1065]
[Origin page](https://www.webcomponents.org/element/mpachnis/mp-video)

To repro:
- open an element's demo page with audio/video, e.g. https://www.webcomponents.org/element/mpachnis/mp-video/demo/demo/index.html
- play the video
- close the dialog

Notice the video is still playing, as the iframe is still in the dom

**Comment by Link2Twenty** [comment]
A quick fix for this would be to clear the iframe's source when the dialog is closed, as it generated the iframe afresh anyway.

```JS
document.querySelector("catalog-dialog#demo-dialog > iframe").src=""
```

**Comment by Link2Twenty** [comment]
This shouldn't be an issue anymore.
