### ISSUE TITLE
Raw Service doesnt serve components outside of github (public gitlab in this case)

### ISSUE THREAD

**Issue by morbidick** [webcomponents/webcomponents.org#1066]
The [demo i just published](https://www.webcomponents.org/element/sangha/sangha-donation-form/demo/demo/index.html) reports a 404 error for dependencies that arent on github (see https://github.com/sangha/sangha-donation-form/blob/master/bower.json#L11). They are publicly available.

They are also not displayed in the dependencies section on the left side.

**Comment by samuelli** [comment]
Hi @morbidick,

We currently don't support anything outside of GitHub. Unfortunately, at this time I don't think it would be worth the technical cost we'd have to incur to support non-GitHub services. We use external services such as [RawGit](https://rawgit.com/) to help us serve content from GitHub.

If support was to be added for other services like gitlab, I think it should be all the way through the stack. eg. you should be able to publish a component from there. At this stage, given the size, I'm inclined to close this for now and reconsider when such a need becomes more popular.

Thanks,
Sam
