### ISSUE TITLE
Styling broken on IE11 and Edge

### ISSUE THREAD

**Issue by ergo** [webcomponents/webcomponents.org#1067]
[Origin page](https://www.webcomponents.org/)

Hi, webcomponents.org is partly broken on MS browsers there are styling problems everywhere, the code snippet text is unreadable, top nav positions are wrong too.

**Comment by TimvdLippe** [comment]
Unable to reproduce on Edge. Working just fine on Microsoft Edge 41.16299.15.0 & Microsoft EdgeHTML 16.16299 with Windows 10.0.16299 Build 16299

**Comment by ergo** [comment]
@TimvdLippe Yes, some time ago edge rendering was fixed.

**Comment by samuelli** [comment]
Thanks @TimvdLippe @ergo

**Comment by ergo** [comment]
Hi, I've got a screenshot illustrating wrong styling on IE11.

https://i.imgur.com/Xa4Jdp0.png
