### ISSUE TITLE
Firefox ServiceWorker installation error

### ISSUE THREAD

**Issue by shawnd** [webcomponents/webcomponents.org#1068]
Firefox 56 reports the following warning:

```TypeError: ServiceWorker script at https://www.webcomponents.org/service-worker.js for scope https://www.webcomponents.org/ encountered an error during installation.```

Not sure if its an issue, I would love for some elaboration.

**Comment by samuelli** [comment]
Thanks for the report.

I'm unable to reproduce this, could you provide any additional info? I'm seeing a successfully activated service worker on Firefox 56.

**Comment by shawnd** [comment]
After conducting more research it seems the warning occurs for people who also have Firefox Nightly installed, and have the service worker installed on both builds.

It appears to be a Firefox issue, nothing more.

**Comment by samuelli** [comment]
Awesome. Thanks for the update @shawnd!
