### ISSUE TITLE
How to list all existed tags (versions) in newly published component?

### ISSUE THREAD

**Issue by limonte** [webcomponents/webcomponents.org#1069]
We just published `vaadin-grid` component: https://www.webcomponents.org/element/vaadin/vaadin-grid

- The current behavior: only latest stable listed in the version selector: 
 ![](https://i.imgur.com/JhhLKof.png)
- The expected behavior: [**all tags**](https://github.com/vaadin/vaadin-grid/tags) are listed in that selector.

How can we achieve all tags listed there?

**Comment by limonte** [comment]
Now there are 3 tags: ![](https://i.imgur.com/lwgem5P.png)

I'm still not quite sure what exactly is happening here :)

**Comment by limonte** [comment]
Ok, it seems that crawler is not in a hurry and doing its job slow and steady :D

![](https://i.imgur.com/BUJRJSn.png)

**Comment by samuelli** [comment]
Yep, it takes a while. For newly published components, we only publish the latest version (3.0.2) and prereleases after that.

Do you need all versions there?

**Comment by limonte** [comment]
> Yep, it takes a while. For newly published components, we only publish the latest version (3.0.2) and prereleases after that.

Thanks for the clarification:+1:

> Do you need all versions there?

It would be perfect, thanks!

**Comment by stramel** [comment]
@samuelli I opened the page for the first time and it showed all the versions in the list. I did a hard refresh now only `3.0.2` and the `4.0` & `4.1` alphas are showing even after a refresh.

**Comment by samuelli** [comment]
This has been fixed for vaadin-grid. Note that I didn't change the actual behavior so this was more of a one-off fix.
