### ISSUE TITLE
Previewers broken

### ISSUE THREAD

**Issue by SieBrum** [webcomponents/webcomponents.org#1070]
Website: https://www.webcomponents.org/preview
Error: 
```
Error - -1
error
An error occured. Please try again.
```

Website: https://www.webcomponents.org/preview-integration
Error: `Failed to create webhook`

**Comment by samuelli** [comment]
Hi @SieBrum,

Thanks for reporting. This was caused by a token error which brought down all the infrastructure. This has now been fixed and has fixed the 2 endpoints you have pointed out.

Thanks.
