### ISSUE TITLE
Markdown button in editing mode not working

### ISSUE THREAD

**Issue by SieBrum** [webcomponents/webcomponents.org#1074]
The markdown button in editing mode (live demo editor) seems to be broken. 

> Not allowed to navigate top frame to data URL

[see](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM)

**Comment by samuelli** [comment]
Thanks for filing this.

Looks like it needs to be updated to initiate a download instead probably. Or it could automatically copy the markdown to clipboard instead. I don't think it makes sense to create any UI for this since its basically a rote transformation.
