### ISSUE TITLE
README.md from outdated google-map.

### ISSUE THREAD

**Issue by nidelson** [webcomponents/webcomponents.org#1077]
Component google-map was updated to v2.0.2, but README.md did not reflect the new version.

**Comment by samuelli** [comment]
It appears to be correct to me.

![image](https://user-images.githubusercontent.com/787668/32973035-41401078-cbaa-11e7-9f9c-a65fa6423ab6.png)

Can you be more specific about what you're seeing?

**Comment by nidelson** [comment]
The component's README.md was updated 2 days ago in v2.0.2, specifically in the `fit-to-markers` property for the plural.
![captura de tela 2017-11-17 as 20 25 02](https://user-images.githubusercontent.com/2224625/32973482-7d0e66aa-cbd6-11e7-8c23-cfb8c7aa23a6.png)

The problem is that when we switch between component versions v2.0.0, v2.0.1 or v2.0.2 on WebComponents.org, it appears that README.md remains the same.

**Comment by samuelli** [comment]
Looks like v2.0.2 was released twice.

**Comment by samuelli** [comment]
Just confirmed, it was released twice so we don't pick up changes. It's being re-released and wc.org will auto-update < 10 mins after that happens.

Thanks!
