### ISSUE TITLE
Why "10.1" instead of "Stable"?

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#1083]
<img width="1125" alt="screen shot 2017-12-01 at 08 02 12" src="https://user-images.githubusercontent.com/1007051/33471528-1b67b7e2-d66e-11e7-9c05-bc699ab246f7.png">

Fiendly ping to @samuelli. 🙂

[Origin page](https://www.webcomponents.org/)

**Comment by samuelli** [comment]
I can't remember why I did that, but I remember doing that lol

**Comment by samuelli** [comment]
PR to change it? :)

**Comment by abdonrd** [comment]
Ok! Haha! 😂

**Comment by abdonrd** [comment]
Check #1084
