### ISSUE TITLE
Version selector is broken in IE11

### ISSUE THREAD

**Issue by limonte** [webcomponents/webcomponents.org#1093]
Reproducible everywhere, e.g. https://www.webcomponents.org/element/vaadin/vaadin-grid

![](https://i.imgur.com/RYQezHf.png)

**Comment by Link2Twenty** [comment]
Looks like this is a limitation of polymer itself

[https://github.com/Polymer/polymer/issues/1735](https://github.com/Polymer/polymer/issues/1735)

TL;DR dom-repeat doesn't work inside certain tags, for IE 11, `select` is one of those tags.

I had a little play and it seems IE copes with the options being placed into the select by javascript so some javascript could be implemented to get IE working.
