### ISSUE TITLE
Header is horizontally misaligned in IE11

### ISSUE THREAD

**Issue by limonte** [webcomponents/webcomponents.org#1095]
![](https://i.imgur.com/WWXAYiq.png)

**Comment by Link2Twenty** [comment]
This line is causing the issue [catalog-app#L89](https://github.com/webcomponents/webcomponents.org/blob/8a24bff7c7ecd38678ade199c21e6b0924e26374/client/src/catalog-app.html#L89).

Removing it centres the header, I tested removing it in chrome too and it had no issues.

**Comment by Link2Twenty** [comment]
Just realised this is a repeat of issue #835

**Comment by limonte** [comment]
Yup, it's a duplicate of #835 which hasn't been fixed for almost 1 year.
