### ISSUE TITLE
Could not find analysis content

### ISSUE THREAD

**Issue by morbidick** [webcomponents/webcomponents.org#1096]
Probably same issue as in #969 and just a random pipeline hickup?

`Could not find analysis content for 0.5.2 in morbidick/paypal-express-checkout` with https://www.webcomponents.org/element/morbidick/paypal-express-checkout/demo/demo/index.html

Thanks for your awesome work!

**Comment by samuelli** [comment]
Looks like these requests were being blocked from one service to another. Redeploying seems to have fixed this and these requests have been fulfilled now.

Link now works.

**Comment by morbidick** [comment]
Thanks @samuelli
