### ISSUE TITLE
Unpublish

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#1139]
Please unpublish all my components listed at: https://www.webcomponents.org/author/arsnebula

**Comment by samuelli** [comment]
Sad to hear that @chrismbeckett. May I ask why?

**Comment by chrismbeckett** [comment]
I appreciate all of the efforts of the webcomponents.org team and yourself Samuel. I have a number of reasons any of which are a basis for my request.

Polymer to me was always something that was meant to melt away as native web components were established. My next generation of components are VanillaJS/Native webcomponents, packaged with NPM.

As I will no longer be using Polymer, I can't continue to maintain and extend my current collection of Polymer components. The repos will remain on Github but I don't feel they warrant promotion on webcomponents.org any further.

It was my belief that webcomponents.org was meant to be a publishing site for any and all web components, but it seems inextricably tied with Polymer, Polymer tooling, Polymer standards, and the Polymer release cycle.

I prefer GitLab over GitHub, and although I can mirror to GitLab for the purposes of publishing to webcomponents.org, I do not prefer doing that.

While my next-gen components will be open-source I will be using a Creative Commons license that does not meet the requirements of webcomponents.org.

I hope this makes sense. I am sorry for the inconvenience. Despite these circumstances, you have my gratitude for all your efforts supporting the web components community.

**Comment by samuelli** [comment]
Hi,

All your published components have been unpublished as requested.

Thanks.

**Comment by chrismbeckett** [comment]
Thx Sam :)
