### ISSUE TITLE
Element won't update

### ISSUE THREAD

**Issue by pedro2555** [webcomponents/webcomponents.org#1140]
[Origin page](https://www.webcomponents.org/element/pedro2555/fsn-map)

I'm sorry if this is a noob question, but I can't seem to update my element by just tagging the github repo.

Tag 0.1.8 has been released hours ago, still not updating on webcomponents.org

I'm I missing something?

**Comment by samuelli** [comment]
Sorry, this should be fixed now!

**Comment by pedro2555** [comment]
Thks!
