### ISSUE TITLE
Add JS Template Literals to browser support table

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [webcomponents/webcomponents.org#1153]
There is a trend of using JavaScript Tagged Template Literals instead of HTML Templates in web components (e.g. using [`html` tag function in Polymer 3.x and 2.4](https://www.polymer-project.org/blog/2018-01-25-polymer-2-4.html), using [lit-html](https://github.com/Polymer/lit-element) or using [hyperHTML](https://github.com/WebReflection/hyperHTML-Element)).

@samuelli What about adding JS Template Literals to browser support table?

**Comment by FluorescentHallucinogen** [comment]
PTAL @justinfagnani @WebReflection

**Comment by justinfagnani** [comment]
I don't think this is necessary. You could end up listing all ES2015 features, and we already have https://kangax.github.io/compat-table/es6/ for that.

**Comment by samuelli** [comment]
Yeah, it also seems pretty well supported in evergreen browsers so I don't think its necessary or particularly tied to web components. If these features are needed by particular libraries, I think its better if they explain browser support for required features.
