### ISSUE TITLE
Elements and Behaviors sections are missing for latest releases

### ISSUE THREAD

**Issue by limonte** [webcomponents/webcomponents.org#1160]
### iron-list v2.0.14

https://www.webcomponents.org/element/PolymerElements/iron-list/v2.0.14

There are  **Elements** and **Behaviors** section in the left sidebar:

![image](https://user-images.githubusercontent.com/6059356/39917782-442a383a-5517-11e8-8eb9-7f916a532cd4.png)

### iron-list v2.0.15

https://www.webcomponents.org/element/PolymerElements/iron-list/v2.0.15

There's no Elements neigther Behaviors section in the left sidebar:

![image](https://user-images.githubusercontent.com/6059356/39917827-68610670-5517-11e8-805c-652e3635ff3f.png)

**Comment by samuelli** [comment]
I believe this is a result of https://github.com/Polymer/tools/issues/330
