### ISSUE TITLE
Search page says "no results for ..."

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/webcomponents.org#1169]
But there are actually plenty of results.

eg. 
![screenshot 2018-05-22 at 22 03 00](https://user-images.githubusercontent.com/539597/40361250-04ea346a-5e0c-11e8-9bc6-25c006eff983.png)

[Origin page](https://www.webcomponents.org/search/color)

**Comment by Link2Twenty** [comment]
I think it should be as simple as adding `totalResults: Number,` to [catalog-search.html#L28-L41](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-search.html#L28-L41)
