### ISSUE TITLE
Could not find analysis content (with polymer 3)

### ISSUE THREAD

**Issue by LarissaAbreu** [webcomponents/webcomponents.org#1178]
Hello :)

I have the same problems as #969 and #1096 .

My component is build with Polymer 3 and haven't any bower dependencie (only NPM).

I created a bower.json for publish my demo but I found this error `Could not find analysis content for 0.2.5 in larissaabreu/up-mushroom`.

My project demo: https://www.webcomponents.org/element/LarissaAbreu/up-mushroom/demo/demo/index.html

I'm using ES modules (don't HTML imports)... How can I do this correctly?

Thanks

**Comment by samuelli** [comment]
I believe this is fixed in our latest update!

Let me know if you're still having issues.
