### ISSUE TITLE
Remove element yooyoo-icon-toggle

### ISSUE THREAD

**Issue by ymedaghri** [webcomponents/webcomponents.org#1187]
This element should be removed because... it was a simple test and I tought there was an automated way to remove it.

**Comment by jsilvermist** [comment]
Are you sure it hasn't been removed? It doesn't come up when I search for it on webcomponents.org.

**Comment by ymedaghri** [comment]
Indeed.
I just deleted the corresponding github repository, is there some automatic synchronization task that is performed periodically to check if github repos referenced by webcomponent have been removed.
It's nice if this is the case.

**Comment by samuelli** [comment]
It's removed automatically!
