### ISSUE TITLE
analysis fails

### ISSUE THREAD

**Issue by jkanche** [webcomponents/webcomponents.org#1188]
I just published an element to webcomponents but notice a spinning wheel on the page 

element page - https://www.webcomponents.org/element/epiviz/data-filter

The call to https://www.webcomponents.org/api/docs/epiviz/data-filter?use_analyzer_data returns a 400. 

issue #1042 mentions maybe this is an issue with `bower install epiviz/data-filter`, but I ran this on a clean directory and see no errors.

any ideas why this is failing?

**Comment by ainvaltin** [comment]
I have the same problem with https://www.webcomponents.org/element/ainvaltin/hwcrypto-button

When opening the page the demo snippet in readme area and "Dependencies" on the left have a spinning wheel and component's documentation and demo links never appear.

On console following is logged:
<pre>
catalog-app.html:18 GET https://www.webcomponents.org/api/docs/ainvaltin/hwcrypto-button?use_analyzer_data 400 ()
send @ catalog-app.html:18
generateRequest @ catalog-app.html:18
_updatePath @ catalog-element.html:9
complete @ catalog-app.html:2
boundComplete @ catalog-app.html:2
_atEndOfMicrotask @ catalog-app.html:2
window.MutationObserver.observe.characterData @ catalog-app.html:2
characterData (async)
run @ catalog-app.html:2
go @ catalog-app.html:2
e @ catalog-app.html:2
debounce @ catalog-app.html:2
_requestOptionsChanged @ catalog-app.html:18
_complexObserverEffect @ catalog-app.html:2
_effectEffects @ catalog-app.html:2
_propertySetter @ catalog-app.html:2
__setProperty @ catalog-app.html:2
_applyConfig @ catalog-app.html:3
_afterClientsReady @ catalog-app.html:3
_ready @ catalog-app.html:1
_readyClients @ catalog-app.html:1
_ready @ catalog-app.html:1
_tryReady @ catalog-app.html:1
_initFeatures @ catalog-app.html:4
__initialize @ catalog-app.html:1
createdCallback @ catalog-app.html:1
window.Polymer @ catalog-app.html:1
(anonymous) @ catalog-element.html:9
catalog-app.html:18 GET https://www.webcomponents.org/api/docs/ainvaltin/hwcrypto-button?use_analyzer_data 400 ()
send @ catalog-app.html:18
generateRequest @ catalog-app.html:18
(anonymous) @ catalog-element.html:9
(anonymous) @ catalog-app.html:2
setTimeout (async)
run @ catalog-app.html:2
async @ catalog-app.html:2
_docsError @ catalog-element.html:9
s @ catalog-app.html:2
fire @ catalog-app.html:2
_handleError @ catalog-app.html:18
error (async)
_listen @ catalog-app.html:2
listen @ catalog-app.html:2
_marshalAnnotatedListeners @ catalog-app.html:2
_marshalAnnotationReferences @ catalog-app.html:2
_initFeatures @ catalog-app.html:4
__initialize @ catalog-app.html:1
createdCallback @ catalog-app.html:1
window.Polymer @ catalog-app.html:1
(anonymous) @ catalog-element.html:9
(index):76 GET https://raw-dot-custom-elements.appspot.com/ainvaltin/hwcrypto-button/v1.0.1/webcomponentsjs/webcomponents-lite.js 404 ()
receiveMessage @ (index):76
postMessage (async)
_setDemoInFrame @ lazy-resources.html:59
load (async)
_setDemo @ lazy-resources.html:59
_complexObserverEffect @ catalog-app.html:2
_effectEffects @ catalog-app.html:2
_propertySetter @ catalog-app.html:2
__setProperty @ catalog-app.html:2
_applyConfig @ catalog-app.html:3
_afterClientsReady @ catalog-app.html:3
_ready @ catalog-app.html:1
_tryReady @ catalog-app.html:1
_initFeatures @ catalog-app.html:4
__initialize @ catalog-app.html:1
createdCallback @ catalog-app.html:1
window.Polymer @ catalog-app.html:1
(anonymous) @ lazy-resources.html:59
(anonymous) @ lazy-resources.html:59
(index):76 GET https://raw-dot-custom-elements.appspot.com/ainvaltin/hwcrypto-button/v1.0.1/hwcrypto-button/hwcrypto-button.html 404 ()
receiveMessage @ (index):76
postMessage (async)
_setDemoInFrame @ lazy-resources.html:59
load (async)
_setDemo @ lazy-resources.html:59
_complexObserverEffect @ catalog-app.html:2
_effectEffects @ catalog-app.html:2
_propertySetter @ catalog-app.html:2
__setProperty @ catalog-app.html:2
_applyConfig @ catalog-app.html:3
_afterClientsReady @ catalog-app.html:3
_ready @ catalog-app.html:1
_tryReady @ catalog-app.html:1
_initFeatures @ catalog-app.html:4
__initialize @ catalog-app.html:1
createdCallback @ catalog-app.html:1
window.Polymer @ catalog-app.html:1
(anonymous) @ lazy-resources.html:59
(anonymous) @ lazy-resources.html:59
</pre>
And after that

    catalog-app.html:18 GET https://www.webcomponents.org/api/docs/ainvaltin/hwcrypto-button?use_analyzer_data 400 ()

is perpetually called / loged. Like once in a second.

How to fix this?

**Comment by clint77** [comment]
Hi,

I have the same issue https://www.webcomponents.org/element/moduware/morph-sidebar/v0.0.2-alpha

I have published other components recently which doesn't have this issue. Any fix to this?
