### ISSUE TITLE
Element docs and demos missing

### ISSUE THREAD

**Issue by ainvaltin** [webcomponents/webcomponents.org#1203]
Published an element https://www.webcomponents.org/element/ainvaltin/hwcrypto-button but it's docs and demo won't appear at the left side menu.

Found similar issue https://github.com/webcomponents/webcomponents.org/issues/726 where it is suggested that the reason for this might be that the component depends on external scripts. The `hwcrypto-button` indeed depends on an external js lib, nameli `hwcrypto.js` which is listed in it's `bower.json` too.

So how to make demo and doc to appear?

**Comment by samuelli** [comment]
We had an issue with our service that runs analyzer.

Looks like yours is fixed now :)
