### ISSUE TITLE
Update polyfills page content

### ISSUE THREAD

**Issue by bennypowers** [webcomponents/webcomponents.org#1214]
The polyfills page at https://www.webcomponents.org/polyfills is woefully out of date. I'm not sure that there's one line of example code that I'd use in a component or app I was writing today. 

I'd like to work on updating that page to reflect the current status of the polyfills. Are all the polyfills' READMEs up to date?

**Comment by samuelli** [comment]
I believe the polyfills' readmes are up to date. PRs very welcome :)

**Comment by samuelli** [comment]
@btopro made a bunch of changes in https://github.com/webcomponents/webcomponents.org/issues/1218. Feel free to send follow up PRs :)
