### ISSUE TITLE
catalog-search-box as a generic webcomponent

### ISSUE THREAD

**Issue by sedainterxion** [webcomponents/webcomponents.org#1224]
We are looking for a webcomponent which works as a suggestion engine, supports remote sources and has templates. [catalog-search-box](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-search-box.html) looks like a good candidate to extract as a generic webcomponent. 

How much work is required to extract it? Would it be ok if we start to extract it for you?

**Comment by samuelli** [comment]
Sure. I'm not sure if its a great idea though, since its tied heavily with Polymer 1, so it's due for a rewrite. Feel free to use it as a template though!
