### ISSUE TITLE
Unable to publish the element.

### ISSUE THREAD

**Issue by Kedar-K** [webcomponents/webcomponents.org#1225]
I recently uploaded it on npmjs but when i try to publish it on web components it gives me this error
![screenshot from 2018-10-10 22-02-09](https://user-images.githubusercontent.com/25702901/46751568-8f101c00-ccd8-11e8-990f-75500cbb6152.png). What should i do to get rid of this error. [This is the npm package](https://www.npmjs.com/package/gradient-button).

**Comment by samuelli** [comment]
Hi,

We currently require it to be linked to a github repository. If you add the repository field and point it to a github repo, it'll work :)

**Comment by Kedar-K** [comment]
Hey it worked!
And my inline demos are not working and even the component is not getting updated after a release. Could you please help me.
