### ISSUE TITLE
https for https://webcomponents.org is unsecure 

### ISSUE THREAD

**Issue by MarcusMorba** [webcomponents/webcomponents.org#1254]
[Origin page](https://webcomponents.org)

![image](https://user-images.githubusercontent.com/22810698/63430535-195afd80-c41d-11e9-942e-948092ee9366.png)

**Comment by MarcusMorba** [comment]
With prefix "www." it works.

**Comment by stof** [comment]
This is unfortunate, because the npm packages use the domain with `www.` as their homepage (well, at least the `template` polyfill)

**Comment by bradjones1** [comment]
This is due to the certificate being valid only for `*.webcomponents.org`, not the apex.

**Comment by justinfagnani** [comment]
This seems to work now.
