### ISSUE TITLE
how to unregister a custom element 

### ISSUE THREAD

**Issue by mohamedafzal03** [webcomponents/webcomponents.org#1294]
[Origin page](https://www.webcomponents.org/community)
HI
to register a custom element, window.customElements.define('my-custom-element', MyCustomElement);
I want to unregister a custom element , is there any possibilities?
like(window.customElements.undefine('my-custom-element')
will be helpful if u guys share your insights.

**Comment by jogibear9988** [comment]
this is not possible at the moment.
maybe this would help in the future: https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry

If you'd like to replace a registered component, you could register a proxy wich then later could replace the implementation.

**Comment by justinfagnani** [comment]
This is a spec question. It's currently impossible to unregister an element (and there are questions about what that would mean). You can see the spec issue here: https://github.com/WICG/webcomponents/issues/754
