### ISSUE TITLE
I've been hacked and this was in my PC's

### ISSUE THREAD

**Issue by jkiller2021** [webcomponents/webcomponents.org#1298]
[Origin page](https://www.webcomponents.org/polyfills/)

4 of my laptops and 3 tablets are hacked. 2 of said laptops have crashed because of it, my isp settings have been altered... I've changed my IP. Tried Norton a closed all ports. NOTHING get these hackers our of my network. Someone please help me.

**Comment by justinfagnani** [comment]
The polyfills are used by many websites. I can't see how they would lead to hacked computers.
