### ISSUE TITLE
Component webpage links to porn

### ISSUE THREAD

**Issue by pamelafox** [webcomponents/webcomponents.org#1319]
[Origin page](https://www.webcomponents.org/element/light-css-framework)

http://nauleau.io/light is now a porn domain, showing NSFW imagery.

**Comment by justinfagnani** [comment]
Oh no... Thanks for bringing this to our attention. The catalog is so little maintained that I'm not sure how to handle this, but I'll escalate right away.

**Comment by justinfagnani** [comment]
Ok, that package has been removed. Thanks for the report!

**Comment by pamelafox** [comment]
Thank you!!
