### ISSUE TITLE
Add Open Graph meta tags

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#381]
I would like to propose add Open Graph meta tags to the different pages (elements, collections, etc) to improve the share experience in social networks, Slack, etc.

Example: [abdonrd/abdonrd.com/index.html#L45-L61](https://github.com/abdonrd/abdonrd.com/blob/develop/index.html#L45-L61)

Card validator: https://cards-dev.twitter.com/validator
Facebook Sharing Debugger: https://developers.facebook.com/tools/debug/

**Comment by samuelli** [comment]
SGTM. @dstockwell: we need to open up the robots.txt before this works.

**Comment by dstockwell** [comment]
I'm not sure how this can work. Twitter appears to process the raw html (doesn't execute JavaScript, upgrade custom elements, etc.)

**Comment by abdonrd** [comment]
Right... The social networks don't execute Javascript. 😕

**Comment by samuelli** [comment]
We can do a generic site-wide card style, but not beyond that unfortunately.

**Comment by CaptainCodeman** [comment]
See https://github.com/Polymer/shop/issues/66 for a related discussion on this.

Adding meta-data works for SEO but not for OG which can often be expected to be read on the client (which is unlikely to run the JS needed to add it). So some server-side rendering is necessary to make it function. There's an example of doing that here: https://github.com/Polymer/shop/pull/78

I also tested it with https://github.com/CaptainCodeman/app-metadata which works for adding meta-data for search-engine bots but not for OG (although support was added in case any web-component server-side rendering system is built).

**Comment by abdonrd** [comment]
We need this! https://github.com/Polymer/news/issues/133#issuecomment-282867975

**Comment by CaptainCodeman** [comment]
I can look at adding this if no one else is working on it - I presume that's what the 'help wanted' tag is?

It will need the index.html to become server-generated at least for the element pages, presumably that'll be OK (some memcache should keep things pretty speedy).

The generic preview that shows up in slack every time someone links to an element is getting a little boring ;)

**Comment by Boscop** [comment]
It looks like on that project they use static pages with the og tags?
What I'm interested in is og tags for dynamic content in single page apps.

**Comment by CaptainCodeman** [comment]
Yes, for this site it will need to inject the tags generated from the datastore entity into the index.html page, using it as a template (for the /element route).

**Comment by samuelli** [comment]
Yup @CaptainCodeman, feel free to dig into this more.

Ideally, these bots should be able to render these pages just fine. An alternate and perhaps more interesting approach is to look at the user agent and serve a generated page if its a bot like Twitter, otherwise fallback to the static serving that is currently used, which is faster.

**Comment by samuelli** [comment]
Also #916. This work is now complete for all `element/`.

Outstanding work:
- [ ] collection pages
- [ ] article pages
- [ ] author pages
- [ ] homepage

**Comment by abdonrd** [comment]
Yay! Good job @samuelli! 👏 

<img width="531" alt="screen shot 2017-04-04 at 11 02 07 am" src="https://cloud.githubusercontent.com/assets/1007051/24649085/2cf61284-1926-11e7-8e55-489900db2df2.png">
