### ISSUE TITLE
Add "copy" button for download command on element page

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponents.org#480]

**Comment by tjsavage** [comment]
& make it scrollable?

**Comment by samuelli** [comment]
Scrollable fixed in #668

**Comment by bkjohnson** [comment]
Can we just leave out the button completely and have the text be copied automatically when you click the bower command?  I'm happy to try this.

**Comment by samuelli** [comment]
Sounds good. Search for `.fire('notify'` on how to trigger a toast.

**Comment by samuelli** [comment]
Added in #940.
