### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#482]
[Origin page](https://beta.webcomponents.org/element/abdonrd/moment-element)

It should appear `moment` as a dependency.

**Comment by samuelli** [comment]
Would it be fine if it was listed but not linked? Right now we don't know the git repo path (we can figure this out later)

**Comment by samuelli** [comment]
#282

**Comment by abdonrd** [comment]
Sure!

**Comment by abdonrd** [comment]
Friendly ping. 🙂

**Comment by samuelli** [comment]
I think this is blocked on #531

**Comment by abdonrd** [comment]
Closing and old issue.
