### ISSUE TITLE
Support NPM/yarn (package.json)

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponents.org#531]
I know that Polymer relies on bower, but much of the front-end community has moved entirely to npm. When developing vanilla js custom elements, there is actually no reason to support bower for many developers.

Therefore it would be very good if:

1. one could publish a component with a package that has only a package.json and no bower.json.

2. when an element is available via npm it should be shown on the right as well.

**Comment by seaneking** [comment]
Echoing this sentiment - we want to start preferencing Yarn at [Simpla](https://www.simpla.io), and also move to webcomponents.org for docs/demos of all our elements.

Don't suppose there's any sense of ETA/priority for this one?

**Comment by seaneking** [comment]
Bump. 

Now that Polymer 2 has landed and is [on NPM](https://www.npmjs.com/package/@polymer/polymer) would be great to see webcomponents.org support Yarn out of the box

**Comment by samuelli** [comment]
Up early @seaneking!

I'm thinking of doing pretty minimal support on the webcomponents.org side:
 * You publish a NPM repository, must be linked to a github repo
 * 1-1 mapping between NPM package and GitHub repo
 * Bower is considered supported if bower.json is found, else just NPM/Yarn
 * NPM package gets installed and analyzed for docs & demo serving

WDYT?

**Comment by seaneking** [comment]
:+1: Sounds perfect for an initial release. Thanks @samuelli!

**Comment by moebiusmania** [comment]
@samuelli I agree with @seaneking , this would be a perfect starting point and a real cross-library support! #usetheplatform

**Comment by moebiusmania** [comment]
@samuelli today I have noticed this on the Bower homepage

> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! 
https://bower.io/

I think that the time has come to start a basic support for NPM registry :)

**Comment by moebiusmania** [comment]
Also, please update the collection publishing process by checking dependencies in ```package.json``` file .

**Comment by samuelli** [comment]
Running list of required technical changes:
- [ ] accept packages #984 
- [ ] update version ingestion to pull from package data
- [ ] update tag lookup to pull from registry metadata
- [ ] update analysis to pull from package and npm install
- [ ] ...more...

**Comment by moebiusmania** [comment]
@samuelli how can we actively help about this? 😊

**Comment by abdonrd** [comment]
Any news?

**Comment by abdonrd** [comment]
Sorry to insist, but, is there any news?

**Comment by moebiusmania** [comment]
@samuelli I know this words could not sounds good, but since the announce of Polymer v3 and the end-of-development on Bower there has been a boost of "interest" and publishing on NPM for Custom Elements folks, so webcomponents.org as a "central hub" for this stuff it's not happening. If this upgrade is something that can be delivered in a month or two **maybe** you can still turn the tide but if there is anything else that is keeping you from working on it (and this is completely legit) I think that should be better to drop it and focus webcomponents.org to be a sort of docs/best practice repo site.

**Comment by samuelli** [comment]
Hey,

Sorry for the delay. There's probably not a great deal of work that needs to be done here. A lot of it has already been done.

Do you have good examples of custom elements published on NPM? That would be helpful in figuring out what's needed to finish this off.

**Comment by abraham** [comment]
I have recently published several custom elements to NPM that I would like to get on WC.org.

https://www.npmjs.com/package/github-repository
https://www.npmjs.com/package/twitter-status
https://www.npmjs.com/package/twitter-user

**Comment by samuelli** [comment]
Perfect, thanks, keep linking more here. That'll be really helpful!

**Comment by abraham** [comment]
Another WC on NPM: https://www.npmjs.com/package/node-package

**Comment by samuelli** [comment]
Hey all,

I'm looking for some testers to test out our implementation so far and help weed out bugs that we might have. If you're interested, sign up here and I'll send out an email shortly. https://goo.gl/forms/qx00rCUkoQiIeFSe2

Thanks for being patient!

**Comment by muelli** [comment]
Anything we can do to help webcomponents arrive in 2018?

**Comment by samuelli** [comment]
Basic support for NPM has arrived to webcomponents.org. There's still plenty of gaps, like #1138, so please file issues for these. Closing this particular issue as you can publish NPM packages to webcomponents.org today. Thanks for your patience!
