### ISSUE TITLE
confusing search tags

### ISSUE THREAD

**Issue by pdgago** [webcomponents/webcomponents.org#673]
It's just me or the tag list looks like a main menu?

I would like two share two alternatives if you don't mind

1. Remove the tags from there and show them in the search-box when the there is no query.
or
2. Make it clear that those links are search tags. Something like this:
![image](https://cloud.githubusercontent.com/assets/1828469/20641861/92aec5ec-b401-11e6-85ad-910823b9431d.png)

**Comment by samuelli** [comment]
Hmm, some analytics:
- tag searches are about 30% of sessions and about 25% of all searches
- most popular search terms heavily influenced by the tags:
```
layout
button
form
paper
toolbar
calendar
paper-
routing
iron
emoji
```

I'd be curious to see what 1. looks like, do you want to try it out @pdgago?

**Comment by pdgago** [comment]
cool, i'll do! 😄
