### ISSUE TITLE
Support for semver v1.0.12-1

### ISSUE THREAD

**Issue by JosefJezek** [webcomponents/webcomponents.org#678]
Could you help me?

Unable to process element - couldn't find any tagged versions

https://beta.webcomponents.org/element/StartPolymer/s-slider
https://github.com/StartPolymer/s-slider

**Comment by samuelli** [comment]
Hmm, that syntax is for pre-release versions: http://semver.org/

I think we should support pre-release branches, but it'll still always default to the latest released branch.

In this case it looks like they are meant to be releases not pre-releases, is that correct? If so, it should be something like v1.0.12.

**Comment by JosefJezek** [comment]
`paper-slider` has v1.0.12 and my fork of this has  v1.0.12-1, I need this versioning... ;-)
