### ISSUE TITLE
a11y: When search list is open, using the arrow keys should navigate through the list

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/webcomponents.org#684]
When I have search results and the focus is in the input, when I press the arrow key down I want to select the first search item. Consequently up and down should move the focus through the items of the list accordingly or back up to the search input

**Comment by bkjohnson** [comment]
This is a dupe of the third list item in #470 right?

**Comment by samuelli** [comment]
Yup! Added an extra item to #470 too.
