### ISSUE TITLE
Publishing is a nightmare

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/webcomponents.org#747]
Hey, 
please fix the publishing workflow.

It is very frustrating and confusing. Somehow I got 2 packages and 1 collection published, but I can not get the other 2 published and I have no idea why. (e.g. this one: https://github.com/nuclei/status-bar)

I have a bower.json, but when I try to publish it, the loading spinner just keeps spinning forever. Refreshing the page shows:

```
Error

Unable to process element
missing bower.json
```

I am sure there is a valid reason for this, but it is just not clear. The preview of my element works fine.

**Comment by web-padawan** [comment]
Your `bower.json` should have a valid semver tag, this can be the reason. 
If so, error message in this case is invalid and confusing.

**Comment by lukasoppermann** [comment]
Hey @web-padawan, this is not correct. Bower does not require or even use a semver tag in the bower.json for at least a year now. It is using the github tags. Besides, this one has non and works: https://github.com/nuclei/material-input/blob/master/bower.json

Thanks for the thought though. 😉

**Comment by dstockwell** [comment]
@lukasoppermann I deleted the element and republished it and it seems to be working now. Did you possibly change the commit that the "v1.1.1" tag pointed to?

**Comment by lukasoppermann** [comment]
Hey @dstockwell, this is possible. Can only you delete and republish elements or can I do this as well? The new version I tagged today worked fine. 

Maybe you could add more tips to the error page when an item can not be published with possible issues, like this one?

I was confused because it had the bower.json and it was showing up fine in the preview, but told me I had no bower.json when publishing.

Thank you for your help. 👍

**Comment by dstockwell** [comment]
> Can only you delete and republish elements or can I do this as well?

For now only site admins can delete. But, publishing a brand new version should be sufficient to kick everything off again.

> Maybe you could add more tips to the error page when an item can not be published with possible issues, like this one?

Yeah, we definitely want to improve the error messages. In this case linking directly to where we expected to find the `bower.json` file would probably have helped track down where this was going wrong. Let's keep this issue open until we have at least that much.

**Comment by samuelli** [comment]
#879 should help, although not exactly linking directly to where we expected to find the file. I'm going to close this issue as fixed. If you spot more issues, let me know!
