### ISSUE TITLE
Proposal: Change custom properties table

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#749]
[Origin page](https://beta.webcomponents.org/element/PolymerElements/paper-input/paper-input-container)

Because the long name or descriptions are more uncomfortable to read. I propose change from:

![screen shot 2016-12-29 at 13 33 11](https://cloud.githubusercontent.com/assets/1007051/21544452/42545052-cdcf-11e6-8568-6ff2f2b81324.png)

To something like:

![screen shot 2016-12-29 at 13 33 11 2](https://cloud.githubusercontent.com/assets/1007051/21544500/c2bc73f0-cdcf-11e6-9f08-0437541c2f9d.png)

**Comment by samuelli** [comment]
SGTM! I think we'll have a second documentation viewer for Polymer to support analyzer anyway, so we can address that at the same time.

**Comment by abdonrd** [comment]
Now with the [iron-component-page v3](https://github.com/PolymerElements/iron-component-page/releases/tag/v3.0.0) published, any news? :)

**Comment by samuelli** [comment]
webcomponents.org now uses the latest iron-doc-viewer. I think, unfortunately it doesn't make sense for us to do much here.

Doesn't look like analyzer looks at CSS custom properties. These tables are just markdown tables, so if we changed it, it should really be changed in the template, not on wc.org itself.

**Comment by abdonrd** [comment]
Closing and old issue.
