### ISSUE TITLE
can't running client

### ISSUE THREAD

**Issue by lstrichashl** [webcomponents/webcomponents.org#766]
I try to run the client.
"dev_appserver.py" file is't exists.
I have tried to run client.py file instead and it doesnt work either way.

**Comment by samuelli** [comment]
Hi,

Instructions are here: https://github.com/webcomponents/beta/tree/master/client

`client.yaml` is the file you're looking for, its under client/

**Comment by samuelli** [comment]
Sorry, I realised you might've been asking something else.

Running the client requires Google App Engine, which can be installed using the [Google Cloud SDK](https://cloud.google.com/sdk/docs/).

Once you have the Cloud SDK installed, install App Engine for Python by running:
```bash
gcloud components install app-engine-python
```
Altenatively, you may install the [App Engine SDK for Python](https://cloud.google.com/appengine/docs/python/download) directly.

**Comment by lstrichashl** [comment]
Thanks for your answer
