### ISSUE TITLE
Not obvious when user hits end of carousel on mobile

### ISSUE THREAD

**Issue by owencm** [webcomponents/webcomponents.org#779]
Low pri

I thought the scrolling in the carousel was just broken when I reached the end as there's no obvious way to tell the end has been reached

**Comment by samuelli** [comment]
@owencm: yeah there's no padding at the end. Is it obvious if there was just some extra space?

![image](https://cloud.githubusercontent.com/assets/787668/21834975/70332d66-d80d-11e6-876b-fa12ef7be8e3.png)

**Comment by samuelli** [comment]
If this is fine, fixed in #789 .
