### ISSUE TITLE
Sections seem to randomly glow blue while scrolling

### ISSUE THREAD

**Issue by owencm** [webcomponents/webcomponents.org#780]
While scrolling down the main page sections under 'Getting started with web components' seemed to randomly glow blue as I scrolled, apparently because touching anywhere on them while scrolling has that affect, at least on iOS.

**Comment by samuelli** [comment]
Hmm, might have to simply remove the `:active` style that the designers gave us for these. Don't really use `:active` anywhere else anyway, so it'll be more consistent.
