### ISSUE TITLE
When swiping through carousel page scroll should be locked

### ISSUE THREAD

**Issue by owencm** [webcomponents/webcomponents.org#781]
When swiping through the carousel in Mobile Safari the page still scrolls vertically, unlike how that pattern works on native apps. This was confusing to me.

**Comment by samuelli** [comment]
Weird. Chrome scroll locks in one direction. Not sure how we would fix this a scroll handler which overrides the scroll behavior.

**Comment by samuelli** [comment]
The only way to fix this would be to add scroll/touch handlers and custom write that behaviour. I'm deeming this as too minor for us to fix reasonably. Sorry!
