### ISSUE TITLE
Not obvious how to find API docs

### ISSUE THREAD

**Issue by kenchris** [webcomponents/webcomponents.org#782]
I found it a bit difficult finding the API docs at first, and I actually stumbled upon them by mistake.

The "API" text is very subtle and I think it should be more prominent. It would also be nice to be able to read the documentation at the same time as playing around with the live view.

**Comment by samuelli** [comment]
Yep, any good ideas on how to unify this in a consistent way?

The challenging part is that some repos have a set of elements. eg take a look at [app-layout](https://www.webcomponents.org/element/PolymerElements/app-layout).

**Comment by tigerhawkvok** [comment]
Better than me -- I couldn't even find the API reference at all! And "Find in Page" didn't find it, either.

**Comment by samuelli** [comment]
@tigerhawkvok: doh that's lame. That one's easily fixable at least. Not sure how to fix the overall problem though.

**Comment by samuelli** [comment]
Hopefully this is much more obvious now :)
