### ISSUE TITLE
Other projects using polymer logo

### ISSUE THREAD

**Issue by kenchris** [webcomponents/webcomponents.org#783]
There is a project using the polymer logo just rotated 90 degrees, which I found very confusing, because I initially though those were new Polymer element groups.

**Comment by web-padawan** [comment]
Do you mean https://github.com/StartPolymer ?
/cc @JosefJezek

**Comment by kenchris** [comment]
Yes that is what I mean. If it is not officially associated with Polymer, it shouldn't use its logo in any way, I would say

**Comment by ebidel** [comment]
cc @tjsavage

**Comment by tjsavage** [comment]
Love the StartPolymer Project. I can see how using the same logo might be confusing. Filed the above issue there to see if we might make the logo a little more visually distinct.

**Comment by JosefJezek** [comment]
@tjsavage Thank you. I will make the logo a little more visually distinct.

**Comment by JosefJezek** [comment]
@kenchris I change the logo now.

**Comment by tjsavage** [comment]
Awesome looks great, thanks @JosefJezek!
