### ISSUE TITLE
New Web Components logo?

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#792]
[Origin page](https://www.webcomponents.org/assets)

This:

<img src="https://web-components-resources.appspot.com/static/logo.svg">

Replaces this logo?

<img src="https://raw.githubusercontent.com/webcomponents/webcomponents-icons/master/logo/logo_256x256.png">

**Comment by samuelli** [comment]
@abdonrd: yep it has!

**Comment by abdonrd** [comment]
Oh! The Twitter need an update! 😅

https://twitter.com/Web_Components
