### ISSUE TITLE
Skate.js link 404s on /libraries

### ISSUE THREAD

**Issue by piperchester** [webcomponents/webcomponents.org#794]
Couldn't see an option to patch this through the GH client. Do I have to clone and build the project to make the fix and open the PR?

**Comment by samuelli** [comment]
Hmm, maybe try cloning and then patching through GitHub then sending a PR?

**Comment by samuelli** [comment]
Our static content and /community lives in a [separate repo](https://github.com/webcomponents/community).

I've fixed this particular issue in a [PR](https://github.com/webcomponents/community/pull/30).

Thanks for reporting @piperchester!
