### ISSUE TITLE
vaadin/vaadin-combo-box is not up-to-date

### ISSUE THREAD

**Issue by limonte** [webcomponents/webcomponents.org#795]
https://www.webcomponents.org/element/vaadin/vaadin-combo-box

Repo: https://github.com/vaadin/vaadin-combo-box

README is different. I performed `Publish your element` action and nothing changed. Is there any cache or something else should be done in order to get the latest README visible on webcomponents.org?

**Comment by web-padawan** [comment]
AFAIK beta versions are not picked up, you need to push a release tag to trigger refresh.

**Comment by limonte** [comment]
Thanks @web-padawan, you're right.
