### ISSUE TITLE
Property annotations are too subtle

### ISSUE THREAD

**Issue by arthurevans** [webcomponents/webcomponents.org#796]
A user on slack noted that they'd missed the fact that annotations like "notifies" and "readonly" appear in the API docs.

https://polymer.slack.com/archives/general/p1484260043014928

Can we make these more prominent? For example, it's especially hard to see the 'notifies' at the end of this long default string: https://www.webcomponents.org/element/PolymerElements/app-route/app-route#property-tail

**Comment by samuelli** [comment]
SGTM.

**Comment by samuelli** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/787668/30234855-7c0b00ee-94b6-11e7-8405-5c6da6b13088.png)
