### ISSUE TITLE
SSL certificate chain is incomplete

### ISSUE THREAD

**Issue by agross** [webcomponents/webcomponents.org#807]
[Origin page](https://www.webcomponents.org/)

See: https://www.ssllabs.com/ssltest/analyze.html?d=www.webcomponents.org

This might cause errors when trying to browse webcomponents.org.

**Comment by samuelli** [comment]
Thanks for the report @agross. Looks like this might be the cause of #804 too. I'll take a look.

**Comment by dstockwell** [comment]
This should be fixed now.
