### ISSUE TITLE
Dynamic refresh

### ISSUE THREAD

**Issue by Najii** [webcomponents/webcomponents.org#808]
[Origin page](https://www.webcomponents.org/community)

Not sure if this is the appropriate place to comment about this, but...the webcomponents.org/community page lazily loads additional content when the page is scrolled to the bottom--ordinarily a very nice feature--but if you are trying to get to the bottom in order to view and click on one of the footer links, it's _really_ frustrating!

**Comment by samuelli** [comment]
@Najii: good point. Any suggestions on how we might fix this? We do this on just a handful of pages but I understand it could be frustrating.

How about it loads once or twice, then shows a button to load more before always loading dynamically for that page?
