### ISSUE TITLE
Safari 10: TypeError: this.createShadowRoot is not a function

### ISSUE THREAD

**Issue by pdesjardins90** [webcomponents/webcomponents.org#812]
The website doesn't work anymore on safari 10, missing polyfill in a recent deploy maybe?

There's that in the console :

TypeError: this.createShadowRoot is not a function. (In 'this.createShadowRoot()', 'this.createShadowRoot' is undefined)

**Comment by Nevraeka** [comment]
@pdesjardins90 Safari 10 only supports v1 (Element.attachShadow) . As to a recent deploy causing this ,  I do not know. I think the v1 polyfill does not work in Safari 10 at all, and we should prob use the Shady DOM shim if we are not already doing that. I'll look and see what we are using

**Comment by samuelli** [comment]
Ahh, this is broken by my vanilla `<progress-bar>`. I'll investigate, not too sure on what the correct usage is.

When using v0 does wc-lite pull in ShadyDom which has v1 syntax?

**Comment by pdesjardins90** [comment]
Seems to be fixed this morning, good job!
