### ISSUE TITLE
Page-level tool-tips

### ISSUE THREAD

**Issue by unfairSurprisery** [webcomponents/webcomponents.org#815]
[Origin page](https://www.webcomponents.org/introduction)

The <catalog-static>s that pages are wrapped in have title attributes which cause page-level tool-tips to appear. This is highly annoying for mouse-readers like me, as it causes tool-tips to appear over the top of content as I'm reading. This behavior is consistent on Chrome, Edge, and Firefox and I've noticed it on the following pages as well:

https://www.webcomponents.org/polyfills
https://www.webcomponents.org/resources
https://www.webcomponents.org/specs
https://www.webcomponents.org/libraries
https://www.webcomponents.org/about

**Comment by samuelli** [comment]
Thanks for the report @unfairSurprisery!
