### ISSUE TITLE
API access intent for on-site catalogue

### ISSUE THREAD

**Issue by seaneking** [webcomponents/webcomponents.org#817]
Hoping to use the webcomponents.org search API to pull in a subset of elements for display at [simpla.io](https://www.simpla.io) - just filing an issue of intent as per [API docs](https://github.com/webcomponents/webcomponents.org/blob/master/API.md).

Simpla is a library of content management components that we're beginning to open up, and we want to encourage the community to publish their Simpla elements to webcomponents.org for docs/demos/etc, but also show a catalogue of them on our site to help discoverability. We'd just pull in names and basic details, then link to the relevant element page on webcomponents.org for full docs.

Are there any limitations around the `/search` endpoint? 

And I was thinking of using the `bower_keywords:` filter to get all elements with a certain tag (eg: 'simpla-element') - is this a good idea? I stumbled across it digging through old PRs, is it public/sticking around?

**Comment by samuelli** [comment]
Hey @seaneking,

Thanks for filing API intent. There's no limitations on our `/search` endpoint. `bower_keywords` sounds reasonable.

I think the better option though would be to [create a collection](https://www.webcomponents.org/publish-collection) & encourage others to send PRs to add it to the collection with a note that it'll also be shown on simpla.io. Then you'll be able to simply use the [collection dependencies API](https://github.com/webcomponents/webcomponents.org/blob/master/API.md#get-collection-dependencies), which should be faster and you'll have more control over what is in the collection if you would like additional requirements before shown in the collection. It'll also mean from any Simpla element, they'll be able to navigate to a view which has all of them.

Thoughts?

I'm going to 'close' this issue, feel free to continue to comment/reach out to me.

**Comment by seaneking** [comment]
Hmm interesting, didn't realise collections had an API as well. Would like to keep 'publishing' a Simpla element as low friction as possible, and adding a keyword to Bower/NPM (in future, hopefully ;-) is pretty common practice (gulp, customelements.io, etc). 

Will explore collections more and report back though, might be the way to go.

/cc @bedeoverend (thoughts?)

**Comment by samuelli** [comment]
Probably not an issue in this case, but with customelements.io, it seemed to be too easy to just add 'web components' as a keyword leading to oft questionable repos.
