### ISSUE TITLE
Show license for a component

### ISSUE THREAD

**Issue by tobireif** [webcomponents/webcomponents.org#818]
Hi :)

What's the license for
https://www.webcomponents.org/element/PolymerElements/iron-swipeable-container
etc?

Tobi

**Comment by samuelli** [comment]
These are [licensed under BSD-3-Clause](http://polymer.github.io/LICENSE.txt)

**Comment by tobireif** [comment]
Thanks for the info.

It would be great if there'd be a link "License" for each component featured on https://www.webcomponents.org/ , which links to the respective (or to the one-and-only) license.

**Comment by stramel** [comment]
I agree it would be nice for it to display a license associated with each package

**Comment by samuelli** [comment]
Thanks for the feedback!

**Comment by samuelli** [comment]
This is live now - let me know what you think.

**Comment by tobireif** [comment]
Wow, that was quick! Each component lists its license, directly on the webcomponents.org page. Fundamentally useful.

Thank you!

**Comment by stramel** [comment]
Thanks @samuelli for the quick addition!
