### ISSUE TITLE
site broken on ipad

### ISSUE THREAD

**Issue by ssatguru** [webcomponents/webcomponents.org#820]
site is unusable when viewed using safari on ipad

**Comment by samuelli** [comment]
@ssatguru: is it just a blank screen or what exactly is broken?

**Comment by samuelli** [comment]
Hi @ssatguru, it seems we don't support older versions of Safari. Are you able to clarify what version of Safari you are using?

**Comment by ssatguru** [comment]
@samuelli 
You are right. But it wasn't just an old version of safari that was the problem. Had the same problem on Chrome too. The problem was I was on an older version of OS . I was using 8.3. I upgraded to 10.2.1 and the problem went away :)

**Comment by samuelli** [comment]
@ssatguru great! We should probably be a bit more explicit about our support.

Closing this issue as resolved.
