### ISSUE TITLE
GitHub issue counter includes pull requests

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/webcomponents.org#826]
The GitHub open issue counter also includes pull requests. At the time of writing, https://www.webcomponents.org/element/TimvdLippe/iron-lazy-pages states that there are 7 open issues. However, there are 5 open issues and 2 open pull requests. Since GitHub treats pull requests as "special" issues, the list of issues also includes pull requests.

What I would expect is that the counter shows there are 5 open issues.

**Comment by samuelli** [comment]
Keen eye @TimvdLippe!

We're currently only looking at the top level [repos API](https://api.github.com/repos/TimvdLippe/iron-lazy-pages) which doesn't give us information.

I think the only way to solve this would be to use the [issues API](https://api.github.com/repos/TimvdLippe/iron-lazy-pages/issues), but it seems a bit excessive to solve the counting issue. Would it be useful to maybe show a list of issues on an element? Or any other stats that might be useful?

**Comment by TimvdLippe** [comment]
Hm not sure, maybe it is easier to just to change the wording to `7 open issues and pull requests in this repository`?

**Comment by samuelli** [comment]
Good point. Would you like to send a PR for that? I'm happy to do it otherwise.

**Comment by TimvdLippe** [comment]
If you do it its probably faster :)
