### ISSUE TITLE
Using dialogs for demos is not great for mobile

### ISSUE THREAD

**Issue by jhuesos** [webcomponents/webcomponents.org#837]
Considering how unfriendly are dialogs in mobile devices, the decision to use them to show the demos in the new site is unfortunate.

Dialogs really don't work well in mobile devices, specially in iOS where they have lots of known issues. I'd like more the previous way, using routing to change the main container to show it.

**Comment by samuelli** [comment]
Routing does change it. What if it was just full screen on mobile?

**Comment by jhuesos** [comment]
Sorry, maybe the wording is not the best. The problematic part is to use any type of container with position:fixed or absolute. If we use a dialog even in full-screen mode, you will have problems in mobile devices.

For example, there as an open issue in Bootstrap for this problem: 
[https://github.com/twbs/bootstrap/issues/19927](https://github.com/twbs/bootstrap/issues/19927)

And basically it says is not a problem with the implementation, it is just a problem with how iOS deals with input fields and dialogs. 

And the two issues related to this problem opened in the WebKit project:
[Bug 158276 ](https://bugs.webkit.org/show_bug.cgi?id=158276#c1)
[Bug 153224](https://bugs.webkit.org/show_bug.cgi?id=153224)

In addition, there is no single dialog on the Internet with a bullet-proof implementation of dialogs. Even paper-dialog has a lot of issue and it has big accessibility issues, like it does not lock the scroll of the background and user can scroll the page bellow the dialog, even with the backdrop enabled. You can test GooglePlus page, angular-material implementation ... all same problem.

I guess my point is: dialogs have A LOT of issues in general, and in mobile are usually unusable unless you use dialogs to show little content without input fields or any complex content. So I think, IMO, using dialogs to show demos is a bad choice and I would rather keep using previous approach from the old catalog.

I can prepare videos to show this defects if needed. And I hope the issue is more clear now.

**Comment by samuelli** [comment]
I see. And to further clarify, this is only on mobile right?

**Comment by jhuesos** [comment]
Yes, dialogs are mostly problematic in mobile devices due to the small screen and lack of space.

**Comment by samuelli** [comment]
Hmm, @jhuesos: a container is always required since demos are rendered in an iframe. The old catalog also used the same approach, using `position: absolute` to fix the container. We can use the same approach, but I'm not sure if this solves the problem you are mentioning.

**Comment by jhuesos** [comment]
as far as I know, most of the problems happen with `position:fixed`, `position:absolute` is fine.

The issue is not when because of the container or the iframe, is when something is position fixed. 

But also I would like to also point out that paper-dialog has quite a bunch of accessibility issues.
