### ISSUE TITLE
Sidebar Navigation like from Polymer Elements Catalog?

### ISSUE THREAD

**Issue by jaakidup** [webcomponents/webcomponents.org#838]
I really enjoyed using the Polymer Elements Catalog.
Everything was grouped together, and the navigation sidebar was easy and fast to use.
Webcomponents however, I find confusing to use, with lots and lots of scrolling needed to find things. (vertical space is wasted as mentioned elsewhere in the issues) 

An even bigger issue now is that, where polymer elements were all pretty much guaranteed to work, they are thrown into a bigger pond of components, that quite frankly don't always work as advertised...

Please keep original site up as well if possible?

**Comment by matthewp** [comment]
Isn't this an issue for Polymer?

**Comment by jaakidup** [comment]
Not really. The Polymer Catalog is being deprecated in favour of the Webcomponents site, it would just be really cool if the Webcomponents site works as well as the other one. Makes sense to want something atleast on par with the old site, I would think.

**Comment by matthewp** [comment]
Sure, but you're not suggesting (in the initial issue) improvements to this site, you're suggesting that the Polymer Elements Catalog be kept up, and this is not the repo for the Polymer Elements Catalog. Your request should be for whoever runs that site.

**Comment by jaakidup** [comment]
I suggest using some sort of sidebar navigation, as seen on polymer catalog...

**Comment by samuelli** [comment]
Thanks for the feedback.

> Everything was grouped together, and the navigation sidebar was easy and fast to use.
> Webcomponents however, I find confusing to use, with lots and lots of scrolling needed to find things. (vertical space is wasted as mentioned elsewhere in the issues)

Can you be a tad more specific? I often found the bundled elements/demos super confusing in the Polymer Elements Catalog.

> An even bigger issue now is that, where polymer elements were all pretty much guaranteed to work, they are thrown into a bigger pond of components, that quite frankly don't always work as advertised...

The [Polymer/elements](https://www.webcomponents.org/collection/Polymer/elements) should mirror the Polymer catalog, is that not sufficient? From a more wholistic view, there's no way the Polymer team can keep up with the number of components & its best suited to an open set of elements from everyone.

**Comment by samuelli** [comment]
Please see updated UI, thanks!
