### ISSUE TITLE
provide API docs

### ISSUE THREAD

**Issue by or9** [webcomponents/webcomponents.org#839]
https://www.webcomponents.org/element/PolymerElements/iron-ajax
Doesn't provide useful info, but redirects the the deprecated site which provides useful info,
https://elements.polymer-project.org/elements/iron-ajax

Doesn't make sense.

**Comment by samuelli** [comment]
Hi @or9,

The API docs are linked on the right-hand side bar:

![image](https://cloud.githubusercontent.com/assets/787668/22408526/5f92a62e-e6ce-11e6-97c4-034d7909aa3b.png)

Cheers,
Sam
