### ISSUE TITLE
Proposal: Fix navigation usability issues on the element page 

### ISSUE THREAD

**Issue by samuelli** [webcomponents/webcomponents.org#840]
Several issues have been filed regarding usability issues on the site:
 * #839 
 * #838 
 * #813 
 * #782 

In summary:
 * Most critically, API docs are hard to find.
 * Vertical space exacerbates this issue, since navigation elements are further down the page.
 * Right-sided navigation - feels odd that buttons on the right affect content on the left. Typical UX means buttons affect content to the bottom and right.

This proposal is for a) moving the sidebar from right to left b) collapsing non-critical information to be dense.

![image](https://cloud.githubusercontent.com/assets/787668/22412624/9691acfc-e704-11e6-8837-d21866fd8dee.png)

Expanded sidebar:
![image](https://cloud.githubusercontent.com/assets/787668/22412628/9e9efb2a-e704-11e6-90aa-a51a67682cd4.png)

**Comment by samuelli** [comment]
Please let me know what you think!
cc/ @tjsavage @dstockwell

**Comment by tjsavage** [comment]
Would the mobile version look the same as today's?

Generally looks reasonable to me. Would love to play with it staged.

Separately - begs the broader question of whether an A/B testing framework would be worthwhile 😄

**Comment by samuelli** [comment]
Mobile version would be the same as desktop now, which is richer than it is currently.
![image](https://cloud.githubusercontent.com/assets/787668/22444093/9d8eebb4-e795-11e6-9fa7-cef9af8ca874.png)


We can do the A/B side, but are there any metrics we're particularly interesting in?

**Comment by tjsavage** [comment]
In this case I think it's probably too early to get meaningful A/B data. But in the longer term I could see having an established way to do this might be useful. But don't want to couple that to this change.

**Comment by samuelli** [comment]
@tjsavage: this is up on [staging](https://custom-elements-staging.appspot.com/element/PolymerElements/marked-element) - use incognito to ensure its not cached by SW.

**Comment by matthewp** [comment]
I like the collapsing non-critical information part of this. the metadata of an element shouldn't be as prominent as it currently is.

But for reasons I can't articulate well, I think having the sidebar on the right is better. Most languages read left to right so having information justified to the left feels more *right* to me. Wish I had a better reason.

**Comment by samuelli** [comment]
@matthewp thanks for the feedback.

Metadata usually flows better in the right. Eg. Npm site. It's less important than the main content.

The key reason I had for shifting it to the left was navigation. Some of the referenced issues highlighted issues finding API documentation which is a critical problem. Navigation typically exclusively lives on the top or left rather the right.

I considered 2 sidebars.. but the seemed excessive.

**Comment by samuelli** [comment]
This has been pushed out at 5% and 30% for a few hours so now I'm pushing it at 100% and closing related issues.
