### ISSUE TITLE
Element Thumbnails

### ISSUE THREAD

**Issue by jhrdina** [webcomponents/webcomponents.org#841]
I think element thumbnails would incredibly improve the user experience. Element lists and search results are now 100% text based. Of course, we have the author avatar icon attached, but it is not very helpful when trying to find out the purpose of an element or what is the difference between say paper-button, ibm-button and nebula-button.

If there are thousands of custom elements in catalog and potentially in search results, I feel like some visual clue would be very handy.

*The element image could be chosen by element publisher*, in the mockup I've used 72x72px size. Element images could be also reused in element-collection cards (see the mockup right side) to give a clue what is inside.

This is just an example, the realization could be completely different, of course...

What do you think?

![mockup](https://cloud.githubusercontent.com/assets/1280734/22425127/ea1497be-e6f9-11e6-9632-f22e23afce76.png)

**Comment by samuelli** [comment]
I love the concept! We've talked about similar ideas previously and there's a couple of sticky points:
 * We want the barrier to publishing an element to be pretty low, the more things we add, the more work it is.
 * Maybe not an issue for UI elements as such, but does it mean you have to update those images all the time?

On the UI side:
 * It can be really challenging to achieve a consistent UI with third party images everywhere. In this mockup, everything uses the same color and style, but that won't be the case
 * To address ^ and also have element thumbnails, this was done on the [Polymer Elements catalog](https://elements.polymer-project.org/browse?view=cards) and it doesn't seem to work well.

Personally, I think my rational for putting this on the back burner before was inline demos are the best indication of what an element does whereas images get you half way. eg. think of large repos like app-layout, animation elements like ken-burns-image, carousel elements. So a lot of my focus has been making switching between elements as fast as possible and hopefully inline demos being the canonical, accurate representation of the element.

Thoughts?
