### ISSUE TITLE
Dind't find bower install command

### ISSUE THREAD

**Issue by nagylakas** [webcomponents/webcomponents.org#848]
The old site was easy to find Bower installation command. On the new interface, I can not find the command for the "platinum-messaging push" element. (the command is: "bower install --save PolymerElements/platinum-push-messaging")

**Comment by samuelli** [comment]
The expand button on the metadata has more info incl download command

**Comment by samuelli** [comment]
Hi, I've updated it to be more obvious where it is hidden, lot me know if this helps!

![image](https://cloud.githubusercontent.com/assets/787668/22576716/4845dffe-ea11-11e6-8300-2cfb95a72b6f.png)

**Comment by nagylakas** [comment]
Thank you very much, I think it is so much better! ☺
