### ISSUE TITLE
No link to GitHub repo on element page

### ISSUE THREAD

**Issue by drigz** [webcomponents/webcomponents.org#849]
I can't find a link to get to the element's GitHub repo from the elements page. There's a button to "Star on GitHub" - perhaps this could be replaced or augmented by a link to the GitHub repo?

![image](https://cloud.githubusercontent.com/assets/632207/22553997/e393c038-e95e-11e6-8657-eafd4f7c1a56.png)

I don't think this used to be the case - was there a redesign recently?

[Origin page](https://www.webcomponents.org/element/PolymerElements/iron-ajax)

**Comment by samuelli** [comment]
Yes, we switched the UI yesterday.

It's actually hidden behind the expand button.

![image](https://cloud.githubusercontent.com/assets/787668/22571669/b7f5e4ec-e9f4-11e6-9b4b-2573145a677f.png)

**Comment by abdonrd** [comment]
Maybe could add a github button before the Web Component name?

**Comment by samuelli** [comment]
I've updated it to be more obvious. Let me know if this works.

![image](https://cloud.githubusercontent.com/assets/787668/22576705/34363e78-ea11-11e6-8c96-ac0ec525ad1f.png)

**Comment by abdonrd** [comment]
Personally, I use the Github button a lot to see the source code.
Could you measure how many people usually press the button? To confirm it is not only me.

**Comment by web-padawan** [comment]
Agree with keeping separate bower and GitHub widgets.
BTW when column gets expanded, those widget are duplicated.
There was a "too much space wasted" issue, but it really used to look better than it looks now.

**Comment by drigz** [comment]
Thanks, samuelli, that's definitely more discoverable. Ideally, I'd prefer the "Star on GitHub" to become a "View on GitHub" - I'd guess "View" gets clicked a lot more than "Star" (~100 times ever even for the most popular components...).
