### ISSUE TITLE
Demo and API Links not displayed

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#853]
[nebula-sidebar-layout](https://www.webcomponents.org/element/arsnebula/nebula-sidebar-layout)

I have published a number of elements and in every case up to now the Demo and API links have been displayed for the elements in the project.

I just published this new element and only the *Overview* of the README is displayed.

**Comment by samuelli** [comment]
I think it's caused by bower.json referencing "nebula-sidebar.html" which doesn't exist.

**Comment by chrismbeckett** [comment]
Ah - nice catch @samuelli :) I was looking through the files wondering where my typo was and scratching my head. Starting at code too long tonight. Thank you.
