### ISSUE TITLE
Update code mirror to fix two colors in the Custom Elements highlight

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/webcomponents.org#859]
[Origin page](https://www.webcomponents.org/element/PolymerElements/paper-menu-button)

<img width="926" alt="screen shot 2017-02-08 at 09 12 21" src="https://cloud.githubusercontent.com/assets/1007051/22728551/ce737408-edde-11e6-93e8-a3dc82f45132.png">

The hightlight show the Custom Elements with two colors instead of one.

**Comment by samuelli** [comment]
Ah, yeah not sure if there's much to do there. The language is set correctly, but this is what code mirror highlights as.

**Comment by TimvdLippe** [comment]
Filed upstream issue https://github.com/codemirror/CodeMirror/issues/4563 :smile:

**Comment by abdonrd** [comment]
Yay! Thanks @TimvdLippe!

**Comment by TimvdLippe** [comment]
Aaand upstream issue fixed :tada: Update CodeMirror once the fix has been published and this issue is resolved :)

**Comment by samuelli** [comment]
You two rock, thanks @abdonrd @TimvdLippe.

I'll close this issue once code mirror is updated.

**Comment by samuelli** [comment]
Proving tricky!

Two issues identified:
 - GitHub's markdown rendering is used in some cases and it has the same issues with dashes in tag names.
 - The code mirror fix doesn't fix the issue and appears to make it worse.

Before
![image](https://cloud.githubusercontent.com/assets/787668/23186609/9b27e706-f83c-11e6-9a27-7a6a2b123bd1.png)

After
![image](https://cloud.githubusercontent.com/assets/787668/23186583/8df7eae0-f83c-11e6-8562-a0b8566aa04f.png)

In fact I think I was incorrect at pointing at code mirror and it was actually correct before. The provided link in the original issue is actually GitHub rendered.

**Comment by TimvdLippe** [comment]
Oh oof. So it is `<marked-element>` that is the problem?

**Comment by samuelli** [comment]
Nope, we use the GitHub markdown API to render it when we process it. I can probably fix this by also highlighting using codemirror

**Comment by samuelli** [comment]
Looks like this has been fixed but not closed - closing.
