### ISSUE TITLE
Wished there would be a Cart System - No Products more Components

### ISSUE THREAD

**Issue by ieim** [webcomponents/webcomponents.org#862]
Hey ya!

First things first. Great job on webcomponents.org, thanks for providing it.

On a regular basis I'm on the elements site from polymer. Usually to look up some definition and how things work. 

Since webcomponents.org's beta I'm planing to dig into the new and bigger components catalogue. 

Now I'm here. Maybe because I'm blind and can't find it or isn't there yet. 

However I'm requesting one thing, what I'm missing. 

A cart where I'm, as a user is, able to add components I'm planning on importing them. 

Like a visitors on a shop site are adding products to the cart, I'd wish I could add components to the cart and copy the bower imports, with ease.

So my request is simple. Is it there and I can't find it or is it on the way coming?

Please, keep up the good work!
Marc

**Comment by samuelli** [comment]
Thanks for the feedback @ieim. I have a couple of questions:
 - did you use the cart functionality on elements.polymer-project.org?
 - would you use this cart functionality multiple times?

With the latter question I'm angling towards potentially vamping up our GitHub starring. So you could then star all the components you like, then view all your starred repos. What do you think?

**Comment by ieim** [comment]
@samuelli thanks for looking into it.

Did I use the cart functionality on elements.polymer-project.org?
1. Yes. The collections on elements.polyer-project.org are fantastic. Its super easy to get multiple and single bower imports.

Would I use this cart functionality multiple times?
2. Yes, I would and did. Maybe its just me or other people are doing it the same way. But ususally for every new project, I'm looking for components I could use and import them one by one. So for every new feature, new project or just diving into a specific component I would use a system like this.

The last part I did not understand. Could you explain it?

**Comment by ieim** [comment]
Hey yaa!

Just saw the great new addition for fast copying bower imports. So this issue is definitely closable.

Thanks. Keep up the good work. 👍
