### ISSUE TITLE
Better search and sorting features urgently needed.

### ISSUE THREAD

**Issue by kshep92** [webcomponents/webcomponents.org#863]
This catalog definitely needs more refined search and sorting features. Searching for `iron-input` returns a list of 825 results with iron-input nowhere near the top. I finally found the PolymerElements page but there's no way for me to sort the elements alphabetically or see them in a grouped fashion.

Finding the elements I'm looking for seems to be more difficult on this website.

**Comment by dstockwell** [comment]
Could you provide a screenshot or a link to the search results page?

Is iron-input not the first result on this page? https://www.webcomponents.org/search/iron-input

**Comment by kshep92** [comment]
@dstockwell If it's all the same to you I'd like to close this issue for reasons to embarrassing to explain. The site is perfect; the error was 100% on my end.
