### ISSUE TITLE
Browsing / Lists

### ISSUE THREAD

**Issue by colohr** [webcomponents/webcomponents.org#865]
I looked at the new site & here is 1 thing that is probably keeping me from using it.

I never search & if I do its Google or the built in text-search.  With this in mind, here is how I would use the new 1:

Clicked on "browse collections" 
Didnt find any sort/order button but I like stuff in alphabetical order.  
I was looking for the iron-components so I assumed maybe Polymer or iron collection.
If i was using this to find docs - I would have stopped the moment I saw the collections where not in alphabetical order.

So thats 1 thing.  Probably no big deal since im sure its quickly accessible through search but it drives me nuts when I dont see things ordered alphabetically - or the option to do so.
  
Ideally it would be like this: https://elements.polymer-project.org/browse?package=iron-elements
Just going to list a few extra opinions:
1. A simple list instead of a grid is more functional to browse items
2. Items look oversized - it looks nice - but you only see a few per page
3. I dont find the need for the logos - also might not benefit smaller devs - I feel people would look over a really good component if they dont see a brand they already know.

Ill stop here because I'm so particular about the stupidest stuff that Im hesitant to post this because Im all about wc's & it would be terrible if I were to get banned or come off as disrespectful.  I do greatly appreciate the effort that people have put into this.

**Comment by jaakidup** [comment]
I totally agree with you about the alphabetical list and oversized items. 
The worst thing is, today when I wanted to use the old elements site, it redirected to the webcomponents site... argh

**Comment by colohr** [comment]
I have it bookmarked and for me it works just fine.  I only use the iron page so maybe thats preventable if you bookmark a particular page.  

On another note I would love to use the new 1 and just kind of see it as a work in progress.  I just hope the old 1 isnt taken down too soon.  

Do you know if the "needed help" tag on the other suggestions is for everyone or just those who are in the group or whatever?  I'm willing to help but I am honestly clueless about all of this as far as github and open source.  I know I can implement my own suggestions, I mean Ive been writing this stuff for over a decade. But at the same time, you for example might be the first developer I've communicated with in my entire life.

**Comment by jaakidup** [comment]
When I click on https://elements.polymer-project.org/browse?package=iron-elements
It actually takes me to the new site... I think the old one is done for... RIP
Yes, the new one is definitely a work in progress for me too, I've been hanging on to elements.polymer for as long as I could. 
It just takes me so much longer to find the things I need, it's almost as if all the organisation has been thrown out the window. I appreciate all the effort they have been putting into the new site, and it will be amazing further down the line.

Same thing here, I've been working in private companies for a long time, and a recent switch to more front-end things have brought me here. So I'm not the best person to ask right now.

**Comment by colohr** [comment]
Issue is resolved for me.

**Comment by samuelli** [comment]
@colohr: what changed?

**Comment by colohr** [comment]
Nothing. I still think the collections should be sorted in alphabetical order but that wasn't the reason I suggested anything.  Now that the old iron elements page is being redirected to the new collection page it pretty much solves all the issues that were keeping me from using it.

**Comment by colohr** [comment]
@samuelli Looks like you are the person that can answer my other question.  Can anyone help? I want to help so let me know.

**Comment by samuelli** [comment]
Yep, its on the radar for compacting the collection page design the same way we did for the element page. Just haven't had time to look into this more yet.

@colohr: if you want to send a PR for sorting sub-collections that'll be great :)
