### ISSUE TITLE
Release title and info (change log)

### ISSUE THREAD

**Issue by Link2Twenty** [webcomponents/webcomponents.org#872]
Should there be a way to see release titles and notes?
It's useful to have a change log of sorts.

(and if you already can, my bad 😉)

**Comment by samuelli** [comment]
Cool idea! What would it look like? Extra link with full change log?

**Comment by samuelli** [comment]
At the same time, this could just link to GitHub though.

**Comment by Link2Twenty** [comment]
Currently, I go to GitHub when I want to see what's been changed but there'd be no need to leave webcomponents.org if there was a way to look at it there.

As for how it would look I'm not sure if it would be better to just show the release notes of the version you're looking at (maybe at the bottom of the Overview or in the sidebar) or  to have a whole page that loads in all previous versions too.

**Comment by samuelli** [comment]
Hmm, I'm a little hesitant to implement this since this would just be a duplication of GitHub's releases page.
