### ISSUE TITLE
Suggestion: Example at each API Reference, for quick copy/paste

### ISSUE THREAD

**Issue by mrsideshowjack** [webcomponents/webcomponents.org#890]
[Origin page](https://www.webcomponents.org/element/PolymerElements/app-layout/app-header#property-scrollTarget)

Underneath each property there could be a example of the property in use inside the element. On click it would add the example to your clipboard, so you can paste it quickly into your element.  for example:

```
debounceDuration
debounce-duration="300" 

```

image shows better example:
![](http://puu.sh/uLsvb/35d370cb43.png)

Currently you can highlight the property name and copy it from there, but this is tricky to do as its a link and for some reason it highlights backwards. Then after pasting it you have to change it from camelCasae to lowwer-case-dash which is tedious.

Personally I would have great use for a feature like this as I copy and paste API properties a lot from the reference.

**Comment by seaneking** [comment]
Not all WCs serialize all properties to attributes, so this would be making an assumption on behalf of the web component author
