### ISSUE TITLE
Resources not loading for tagged release

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/webcomponents.org#897]
I've tagged v0.1.0 for my `stock-value` element, but resources don't get loaded in [the webcomponents.org page of the element](https://www.webcomponents.org/element/valdrinkoshi/stock-value)
```
GET https://user-content-dot-custom-elements.appspot.com/valdrinkoshi/stock-value/v0.1.0/stock-value/stock-value.html 404
GET https://user-content-dot-custom-elements.appspot.com/valdrinkoshi/stock-value/v0.1.0/webcomponentsjs/webcomponents-loader.js 404

**Comment by samuelli** [comment]
Fixed now for your one. Looks like there are 46 other ones in the same situation. Something seems to be causing analysis service to lock up. Looking into it further.
