### ISSUE TITLE
Header "example searches" aren't really links

### ISSUE THREAD

**Issue by stuartlangridge** [webcomponents/webcomponents.org#905]
The header "links" which perform a search -- "button", "notification", "media", "toolbar", and "image" -- aren't _actually_ links; they're `href="#"`. This means that a middle-button click on them (to open those searches in a new window while you're still reading things on the page you're on) will just open up a new tab pointed at the page you're already looking at, not a page of actual search results.

(If the plan is that they aren't supposed to be links at all and you're supposed to click them and then read results in the popup, and a list of search results of web components is not intended to be a thing that people link to, then maybe they should be `<button>`s or similar so that middle-click doesn't do anything, rather than doing the wrong thing?)

**Comment by samuelli** [comment]
Good point - they can easily link to the search page.
