### ISSUE TITLE
webcomponents.org demos don't seem to work right

### ISSUE THREAD

**Issue by stuartlangridge** [webcomponents/webcomponents.org#906]
In trying to get a sense of whether web components are something I want to get more involved in, I tried to look at some demos of existing components on webcomponents.org, but I've basically been unable to find any that work. Some examples:

* https://www.webcomponents.org/element/PolymerElements/iron-image has a link which says "Demo and API docs" which seems to link to the same page I'm on
* https://www.webcomponents.org/element/jifalops/from-now has a link saying "full demo: webcomponents.org" which opens up a popup reading "could not find analysis for 0.3.1 in jifalops/from-now"
* https://www.webcomponents.org/element/acordeonl/local-dom has a "demo" link in the sidebar which opens up a popup that doesn't seem to work

Maybe I'm just unlucky, and it's entirely possible that this isn't webcomponents.org's fault and what I'm doing is blaming the telephone company because I got phone calls I didn't like, but it's not given me a very rosy view of the current state of the art. (If making this stuff work is the responsibility of the component publishers and webcomponents.org is just a store front, then feel free to close this, although if so that could perhaps be clearer?)

**Comment by samuelli** [comment]
* iron-image - we should probably strip out existing self-references, but this is non-trivial since they vary; badge, link etc. The demo in the left sidebar works fine.
 * from-now - looks like analysis from that got broken. I manually retriggered it and it seems to be working now! Let me know if there's others like this.
 * local-dom - unfortunately this element is broken and its best to file an issue with the author.

**Comment by felixzapata** [comment]
@samuelli I do not know very well if it is related but with [this component](https://www.webcomponents.org/element/felixzapata/polymer-openajax-datepicker/demo/demo/index.html) the demo does not work with the version 0.2.0. 

When you open it, it says there is an error with the analysis. I am sure that there is something wrong with the demo that the analysisi can´t complete.  

Is there a way to check this analysis for the demo? The only different with previous versions is with the new version there is another example inside the demo.

**Comment by samuelli** [comment]
@felixzapata: looks like there's a conflict on install.
polymer: Unable to find suitable version for polymer

Try cloning & bower install.

**Comment by felixzapata** [comment]
mmm it is weird. I made a fresh install before publishing the new version. I will take a look. Thanks

**Comment by felixzapata** [comment]
Hi @samuelli, I cloned it again and I've made a bower install in another computer and there is no conflict.

**Comment by samuelli** [comment]
@felixzapata: I'm still seeing the conflict.
![image](https://user-images.githubusercontent.com/787668/27611119-ce3028ea-5b45-11e7-97dc-0a8831348b19.png)

@abdonrd: are you able to update moment-element to a range like "polymer#1 - 2"? eg. https://github.com/PolymerElements/app-layout/blob/master/bower.json#L23

**Comment by abdonrd** [comment]
@samuelli sure!

**Comment by samuelli** [comment]
Let me know once you do @abdonrd :)

**Comment by abdonrd** [comment]
@samuelli released `moment-element` as hybrid element! :)

**Comment by samuelli** [comment]
Awesome. @felixzapata: you'll need to update to point to latest moment-element from @abdonrd :)

**Comment by abdonrd** [comment]
@samuelli @felixzapata I send a PR for that: https://github.com/felixzapata/polymer-openajax-datepicker/pull/9

**Comment by felixzapata** [comment]
@samuelli @abdonrd thank you guys. I´ve released version 0.2.1
