### ISSUE TITLE
iron-meta-query docs

### ISSUE THREAD

**Issue by javatheist** [webcomponents/webcomponents.org#909]
[Origin page](https://www.webcomponents.org/element/polymerelements/iron-meta)

Hi Team, i'm pretty sure that i'm not the first one... are you guys still elaborating the iron-meta-query docs which equal the iron-meta docs in every single letter? just mentioning ;)

Awesome project, thx for all your effort so far.

best regards, p

**Comment by samuelli** [comment]
This has been fixed, thanks!
