### ISSUE TITLE
Collection not showing dependencies: simpla-elements

### ISSUE THREAD

**Issue by seaneking** [webcomponents/webcomponents.org#910]
Bug with a particular collection: [simpla-elements](https://www.webcomponents.org/collection/simplaio/simpla-elements) ([repo](https://github.com/simplaio/simpla-elements)). Should show 3 elements in the collection at the moment, but not showing any (though when searching it says it has 3 items - not visible on page or via `dependencies` API).

Am I missing something? You just add the elements as deps to `bower.json` right? Thought it might be a caching issue but last commit was several hours ago.

**Comment by samuelli** [comment]
I think its the `latest`. Best to just use `"simpla-text": "simpla-elements/simpla-text"`.
See: https://github.com/PolymerElements/iron-elements/blob/master/bower.json

**Comment by seaneking** [comment]
Yep that fixed it - why is that the case? `latest` is a supported version name as of Bower 1.2.something

**Comment by seaneking** [comment]
And if this is a known bug should there be a note in the collection publishing page? Can see it catching people out (like me ha)

**Comment by samuelli** [comment]
Probably should be a note! Want to send a PR? Not sure what wording would be best.

https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-publish-collection.html

Probably a bit too minor to fix at this point. Particularly if we change to NPM... one day...

**Comment by seaneking** [comment]
Hopefully one day soon! Just noticed that Bower have effectively put a deprecation warning on their site asking users to move to Yarn. Chomping at the bit to move entirely to Yarn as our recommended workflow for Simpla.

And sure thing will submit a docs PR

**Comment by samuelli** [comment]
Yep, unfortunately you'll have a dependency on bower till all these components are up on NPM. Till then you can add `bower install` to your NPM commands for a 'yarn-like' workflow.

**Comment by samuelli** [comment]
That being said, if you have good insights into using Yarn etc, share with us/community would be great!

**Comment by seaneking** [comment]
Well, we wouldn't be using NPM since wc distributed as HTML imports (as ours are) need a flat dep structure unfortunately. So, Yarn FTW!

Yarn can pull unpublished packages from Github, but there's some oddities around versions (eg: installing Polymer this way doesn't work)

```
yarn add [user]/[element]#^[version] --flat
```

To be honest WC distribution is a bit of a mess atm IMO. I think either the community needs to standardize on HTML imports (or HTML Modules or whatever the v2 is being called) and build tooling around that, or move to JS-only distribution. We've run into so many headaches trying to sort out how our ecosystem is going to work.

Oh, and just had a squiz at the client... bit of grunt work to get it running locally, that PR might be a weekend job ;-)

**Comment by samuelli** [comment]
On the client it should just be installing app engine and running `client/client.yaml`. Otherwise, feel free to just send a PR modifying the text, no need to really run it.

Distribution: yep, probably our biggest challenge right now, known issue but no good answers yet!

**Comment by seaneking** [comment]
Ah okay cool, will do

**Comment by seaneking** [comment]
This particular issue is fixed, so closing
