### ISSUE TITLE
slim.js

### ISSUE THREAD

**Issue by eavichay** [webcomponents/webcomponents.org#924]
[Origin page](https://www.webcomponents.org/publish-collection)

I'd like this library to be added to your registry of libraries.
slim.js empowers web components with inheritance thus making a slim layer of code very powerful.

github: eavichay/slim.js
http://slim.js.org

**Comment by samuelli** [comment]
Awesome! Mind sending a PR for this file?

https://github.com/webcomponents/community/blob/master/static/libraries.md

**Comment by eavichay** [comment]
https://github.com/webcomponents/community/pull/36 <https://github.com/webcomponents/community/pull/36>
