### ISSUE TITLE
New custom pages feature not rendering

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#925]
I am trying to use the feature introduced in #908, but the content of the markdown page isn't rendering. I tried it yesterday but I had not tagged the repository and from comments in the code it says something about "version required". So now I have a tagged release and am ready to publish, but the doc page is still not rendering. It appears in the box, but clicking the item is a blank page.

![wc-pages-issue](https://cloud.githubusercontent.com/assets/6036093/24920593/a87ef3aa-1e9c-11e7-846f-0aea52e81c65.png)

The repo I am using is: https://github.com/arsnebula/nebula-element-mixin

**Comment by samuelli** [comment]
Yep, I noticed yesterday that there were some bugs in the implementation.

It does seem to work after a refresh though.

https://www.webcomponents.org/preview/arsnebula/nebula-element-mixin/ea1568c3d37bc5fee55e4b96173f831af7ed82e5/page/docs/nebula-element-mixin.md

I'll send out a fix.

**Comment by chrismbeckett** [comment]
Thanks for the confirmation Sam, that helps a lot. I have a lot of additional elements to finish updating and publish for v2, and I needed to know I wasn't configuring them wrong before I push tagged releases.

**Comment by samuelli** [comment]
@chrismbeckett:

[Preview](https://www.webcomponents.org/preview) & [GitHub integration](https://www.webcomponents.org/preview-integration) are your friends. That way you won't need to push any tagged releases till you're certain its ready to go.

**Comment by chrismbeckett** [comment]
@samuelli So, you can preview custom pages on a branch that does not have a version tag? I thought I saw a comment in the code that said that a version tag in the location URL was required?

**Comment by samuelli** [comment]
Hmm. You may need one tagged version across the whole repository. Then any preview of pull request/commit/tag/branch URL should work without any new tags.

**Comment by chrismbeckett** [comment]
Ok - for new components I will make sure I push a prerelease tag and verify it before I push a release tag to be safe (I should be doing it anyway, but like everyone - so much work to do). Thanks :)

**Comment by samuelli** [comment]
Ideally it shouldn't be necessary, but it may have just been the way it ended up being written since preview functionality was added afterwards.

**Comment by samuelli** [comment]
BTW, if you can review #926, I can merge it.

**Comment by chrismbeckett** [comment]
Thanks for your help Sam.
