### ISSUE TITLE
Markdown ## headers being stripped from custom documentation page

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#928]
This is a weird one, but I have updated my markdown document a few times to verify. If you are using the new custom pages feature, and the markdown file has a `##` header line, it gets removed during rendering.

UPDATE: If I change the `##` and use HTML `<h2>` then it works. Seems like it might strip `#` headers as well.

**Comment by samuelli** [comment]
Hmmm, yeah.

We should probably fix this in a better way. Because of a lot of readmes duplicate the title of the repo in it, I wanted to hide it in those cases. So this is the source in question, which doesn't work well for guides.

```
article.markdown-body > h2:first-of-type, article.markdown-body > h1:first-of-type {
        display: none;
      }
```

**Comment by chrismbeckett** [comment]
Ah, I just came back to update that using h2 doesn't solve it. It seemed to work because I put two headers in a row. Based on your info above, that makes sense - it only hides the first one.

Ok, well, easy enough to work-around for now, I will just divide up my overview to add an extraneous header so that the doc looks ok whether it display or not. Thanks for the info.

I see the wisdom in hiding the first h1, since most README's just about always start with the repo name. Why hide the first h2? In my README's (following the sample for publishing), it is usually the `## Installation` block that ends up having the header trimmed.

**Comment by seaneking** [comment]
I noticed this too (see https://github.com/webcomponents/webcomponents.org/issues/988). Echoing @chrismbeckett, what's the rational for hiding h2 first-of-type? I would hazard a guess that the use case of using h2s in a README for subheadings is far bigger than using a h2 for the main readme title.

**Comment by seaneking** [comment]
That said, more robust solution would be to do a simple regex check for h1/h2 that contains element name with JS. In the meantime though I think a quick fix for the majority case would be to just remove the h2 decl. Feels pretty buggy for most pages right now

**Comment by samuelli** [comment]
I've been pretty swamped working on other things, so if someone wants to take a look and send a PR that'll be greatly appreciated :)

Otherwise, I'll take a look whenever I can.

**Comment by seaneking** [comment]
👍 Happy for a PR to just ignore h2's for now?

**Comment by samuelli** [comment]
Sure. Or the regex you described above if its the exact same name.

**Comment by seaneking** [comment]
https://github.com/webcomponents/webcomponents.org/pull/997

**Comment by seaneking** [comment]
@samuelli Example of the regression #1000 caused (originally flagged in #997 ):

<img width="828" alt="screen shot 2017-06-29 at 1 48 02 pm" src="https://user-images.githubusercontent.com/6374876/27686148-bdebb85e-5cd1-11e7-8234-f3cbb8a13e15.png">

Could we reinstate the simple regex match check over literal `component-name` string? eg:

```js
// yields /component[ -]name/i
var elementNameExp = repo.split('-').join('[ -]');
var headingsRegex = new RegExp(elementNameExp, 'i');

// Matches component-name, component name, Component Name, etc
firstHeading.textContent.match(headingsRegex);
```
