### ISSUE TITLE
Polymer 2.0 - dependency update frequency

### ISSUE THREAD

**Issue by rene-lindner-isw** [webcomponents/webcomponents.org#931]
Hi,

How often get the dependencies updated for the 2.0 element demos?

e.g. Polymer team changed iron-dropdown#2.0-preview that the content needs an slot name - updated my element according to it. However my webcomponents demo uses still the old iron-dropdown#2.0-preview version.
https://github.com/PolymerElements/iron-dropdown/commit/6b2bbb9558b32f7b51801be329f5c3ef795b1822

For the paper-input#2.0-preview i still get a bug that is already fixed.
https://github.com/PolymerElements/paper-input/commit/7a5a24815717cdc05643ebc9d52d103000b45642

Demo:
https://www.webcomponents.org/element/IswPolymerElements/isw-dropdown-menu/demo/demo/index.html

**Comment by samuelli** [comment]
I don't think they ever get updated. For your tagged release 1.0.7, the dependencies shouldn't ever change to ensure that it'll always work.

Tagging a new release should be sufficient to get your deps updated. Have you tried that?

BTW, you can also use custom demos so it shows up in the sidebar. See #899.

**Comment by samuelli** [comment]
Also I should add that once Polymer 2.0 is properly released, these elements will be properly versioned which will probably help make this less confusing.

**Comment by rene-lindner-isw** [comment]
Drafting a new version helped now, but don't know why it didn't worked with the 1.0.7, this release was also after the fixes in the 2.0-preview branches.

thanks for the hint with the demo, thought @demo was the only way and waited for 2.0 to be supported. Will have a look at it :)
