### ISSUE TITLE
Remove https://www.webcomponents.org/element/GeoloeG/geoloeg-elements

### ISSUE THREAD

**Issue by MeTaNoV** [webcomponents/webcomponents.org#934]
Hi,
I didn't find a way to do it on the website but I would like to remove the following element `geoloeg-elements` to be able to migrate it as a collection or migrate it directly to the associated collection.
Thanks in advance!
Cheers,
Pascal

**Comment by samuelli** [comment]
Hi,

You can actually migrate it to a collection directly if you like. You would just need to add "element-collection" to your bower keywords and add elements as dependencies. More info on collections: https://www.webcomponents.org/publish-collection

If not, I can remove it anyway.

**Comment by MeTaNoV** [comment]
I did it but forgot to push my commit! Migration is indeed successful! Thx!
