### ISSUE TITLE
overview not displaying because "content is too large"

### ISSUE THREAD

**Issue by christophe-g** [webcomponents/webcomponents.org#938]
Hey, 

Is there a limit for the size of documentation content that prevents the overview to be displayed in some cases? I have trouble displaying API and demo for two components I wish to register : https://www.webcomponents.org/element/PolymerEl/multi-verse and 
https://www.webcomponents.org/element/PolymerEl/multi-chart?

It seems it tries to load docs from  https://www.webcomponents.org/api/docs/PolymerEl/multi-chart? - which returns http 400 with this error code: "content was too large: 599820".

Thanks,
C.

**Comment by samuelli** [comment]
Yep there's a limitation on how much we can store per properties in our datastore. Looks like it's just reaching the limit. I've taken a look and it seems like this could be avoided if we can manage to do some compression, which I'll take a look into.

An upcoming change will also reduce what we store, which will likely fix this particular case.

**Comment by samuelli** [comment]
Fixed now. If you reload [multi-chart](https://www.webcomponents.org/element/PolymerEl/multi-chart) all the docs are there.
