### ISSUE TITLE
Custom Demo Link - bower.json

### ISSUE THREAD

**Issue by rene-lindner-isw** [webcomponents/webcomponents.org#946]
Hi,

Published a new element:
https://www.webcomponents.org/element/IswPolymerElements/isw-responsive-behavior

I want the demo to be full-screen, not in an overlay, so i set up an Github Page:
https://iswpolymerelements.github.io/isw-responsive-behavior/demo/index.html

Added the demo link to the bower.json:
```javascript
{
  ...
  "demos": {
    "Demo": "https://iswpolymerelements.github.io/isw-responsive-behavior/demo/"
  }
}
```

But the demo button now opens an overlay with an error:
could not fetch: https://cdn.rawgit.com/iswpolymerelements/isw-responsive-behavior/1.0.0/https://iswpolymerelements.github.io/isw-responsive-behavior/demo/index.html

Can i set the demo to an custom url?
Can i set the demo to open in a new window and not in an overlay?

**Comment by samuelli** [comment]
> Can i set the demo to an custom url?

Not currently, but this is something we could probably support pretty easily.

> Can i set the demo to open in a new window and not in an overlay?

No, and I'm not really sure what a good way to specify that behavior would be.

What if we supported absolute paths which always opened in a new tab? In a way that kind of makes sense since wc.org is no longer hosting the demo. However this means there's no choice involved. What do you think?

**Comment by rene-lindner-isw** [comment]
Would work really well for my demo, and in generel i think it's ok.

**Comment by dstockwell** [comment]
> What if we supported absolute paths which always opened in a new tab?

I think this is preferable. In general, the content presented on the site is tied to a specific version of the element's repo, for external URLs we have no way to ensure this so this seems like a fair trade off.

**Comment by rene-lindner-isw** [comment]
For my case, if i could specify the demo to open in a new tab, there would be no reason for me to use an external demo.

I only used an external demo because i expected 

> What if we supported absolute paths which always opened in a new tab?

this behavior.

For me, if you provide me any way to make the demo in a new tab, so i can be sure users can correctly test the responsive features with the google chrome device toolbar, i'll be happy. But no need for an extern demo would be really awesome.

**Comment by samuelli** [comment]
I see. We have seen related situations though.

cc @ffu, would this be useful for app-layout?

**Comment by Pupix** [comment]
Any news on this? I've got the same problem. The links being read properly but the `gitraw` approach  breaks everything.

[Example link](https://www.webcomponents.org/element/expandjs/mat-elements/demo/https://expandjs.com/components/mat-breadcrumb/demo)
