### ISSUE TITLE
webcomponents.org seems to be broken

### ISSUE THREAD

**Issue by ttsvetko** [webcomponents/webcomponents.org#947]
Components' pages do not show any properties, events or methods.

[Origin page](https://www.webcomponents.org/element/PolymerElements/paper-input/paper-input#events)

**Comment by alejost848** [comment]
I can confirm. As soon as I clicked refresh in the "There is a new update available" toast, the website broke.

![error](https://cloud.githubusercontent.com/assets/8323249/25489884/dcd2b880-2b30-11e7-8df7-14a7f60a491b.JPG)

**Comment by abdonrd** [comment]
cc @samuelli

**Comment by samuelli** [comment]
Thanks for the report!

Apologies - it seems it was broken in #935. This is fixed in #950 which is now deployed. If you load the new update it should be resolved.
