### ISSUE TITLE
Unpublish Request

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#948]
I have two published components that are being deprecated. Can I please have these components unpublished from webcomponents.org.

[nebula-splitview](https://www.webcomponents.org/element/arsnebula/nebula-splitview)
[nebula-style-attributes-behavior](https://www.webcomponents.org/element/arsnebula/nebula-style-attributes-behavior)

**Comment by samuelli** [comment]
Done. Note it might be a bit funky with the service worker.
