### ISSUE TITLE
Missing Sub-Collections

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#949]
I have a top-level [nebula-essentials](https://www.webcomponents.org/collection/arsnebula/nebula-essentials) collection that only contains sub-collections (no individual elements). The sub-collections don't seem to be displaying anymore (the collection appears empty). The one change made recently was to add semver ranges to the sub-collections where I used to use either 'latest' or '*'.

```
  "dependencies": {
    "nebula-app-essentials": "arsnebula/nebula-app-essentials#^2.0.0",
    "nebula-ui-essentials": "arsnebula/nebula-ui-essentials#^2.0.0",
    "nebula-dialog-essentials": "arsnebula/nebula-dialog-essentials#^2.0.0"
  }
```

**Comment by samuelli** [comment]
@dstockwell might have some more details, but I think our recommended approach for collections is to not use any semver. eg. just point to "arsnebula/nebula-app-essentials". Is that possible?

**Comment by chrismbeckett** [comment]
Sure - I will make that change. Thanks :)
