### ISSUE TITLE
Element documentation not displayed for scary-cookie-consent

### ISSUE THREAD

**Issue by Scarygami** [webcomponents/webcomponents.org#956]
Hi,

I've been trying to figure out why one of my elements, [`scary-cookie-consent`](https://www.webcomponents.org/element/Scarygami/scary-cookie-consent) doesn't get the documentation displayed, but I couldn't find any differences to other elements I've published which have their documentation displayed correctly.

The API response returns an empty `"elementsByTagName": {}` so there's probably some problem with the analyzer (either because of a bug in the analyzer or because of something wrong in my jsdoc)

The documentation get's displayed correctly via [`iron-component-page`](https://scarygami.github.io/scary-cookie-consent/)

Would be nice if someone could take a look what might cause this problem :)

Thanks.

**Comment by Scarygami** [comment]
Not sure if you changed something, or if I changed something, but it works now :)

**Comment by samuelli** [comment]
Looks like you fixed it! 👍
