### ISSUE TITLE
Properties should be also listed in "allow-outside-scroll" format

### ISSUE THREAD

**Issue by bubersson** [webcomponents/webcomponents.org#965]
Properties should be also listed in "allow-outside-scroll" so those are easy to copypaste in the code. 

[Origin page](https://www.webcomponents.org/element/PolymerElements/iron-dropdown/elements/iron-dropdown#property-allowOutsideScroll)

**Comment by samuelli** [comment]
Thanks! Duplicated on https://github.com/PolymerElements/iron-doc-viewer/issues/125.
