### ISSUE TITLE
Images are not shown in demo page

### ISSUE THREAD

**Issue by ThomasCybulski** [webcomponents/webcomponents.org#966]
Hi,

Since yesterday, I have a problem with images on the demo page, as you can see in the screenshots below and my [custom element](https://github.com/ThomasCybulski/paper-chip). What I'm doing wrong?

![Message1](https://raw.githubusercontent.com/ThomasCybulski/ThomasCybulski.github.io/master/paper-chip/img/error/error.PNG)

![Message2](https://raw.githubusercontent.com/ThomasCybulski/ThomasCybulski.github.io/master/paper-chip/img/error/github_demo_source.PNG)

Thanks!

**Comment by samuelli** [comment]
Looks like a bug!

**Comment by ThomasCybulski** [comment]
@samuelli 
It seems the bug is still there. You can see it in my component preview: https://www.webcomponents.org/element/ThomasCybulski/paper-chip

**Comment by samuelli** [comment]
Hi,

See https://raw-dot-custom-elements.appspot.com/ThomasCybulski/paper-chip/1.1.1/paper-chip/demo/avatar.png which works fine.

The issue is your image is pointing to /demo/images/ which is a folder which doesn't exist.

**Comment by ThomasCybulski** [comment]
Hey,
many thanks! I forgot to take a look into the readme.md.
