### ISSUE TITLE
Could not find analysis content

### ISSUE THREAD

**Issue by raulsntos** [webcomponents/webcomponents.org#969]
I am getting the error `Could not find analysis content for v0.0.9 in raulsntos/noto-emoji-iconset`. It also happens in version 0.0.8.

I don't know if there is something I have to do to make it work or if it's an issue with webcomponents.org, the element worked before.

**Comment by samuelli** [comment]
Hi @raulsntos, this should be fixed now. For some reason this particular element was throwing an exception in one of our pipelines, so it was stuck there. That part was just disabled and your element seems to be fine now!

Apologies for any inconvenience!
