### ISSUE TITLE
Failed to load resource ... (?use analyzer data)

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#970]
The `catalog-element` web component is failing to render on a bunch of my components on webcomponents.org (ex. https://www.webcomponents.org/element/arsnebula/nebula-dialog).

The developer console shows repeated errrors with GET requests to:

https://www.webcomponents.org/api/docs/arsnebula/nebula-dialog?use_analyzer_data

**Comment by samuelli** [comment]
This part is fixed now - apologies!
