### ISSUE TITLE
Properties inherited from behaviors not considered

### ISSUE THREAD

**Issue by rictic** [webcomponents/webcomponents.org#972]
_From @andreasanheuser on May 17, 2017 0:20_

See e.g. paper-tabs documentation: https://www.webcomponents.org/element/PolymerElements/paper-tabs/elements/paper-tabs

`selected` property is not listed under API.

_Copied from original issue: Polymer/polymer-analyzer#680_

**Comment by rictic** [comment]
This looks like a webcomponents.org issue, as I see `selected` when I analyze locally.

Repro:

```bash
git clone https://github.com/PolymerElements/paper-tabs.git && cd paper-tabs && bower install && polymer analyze | grep selected
```

**Comment by andreasanheuser** [comment]
Thanks for moving this to the right repo + the quick fix! :-)

**Comment by samuelli** [comment]
No worries. This particular instance should be fixed now but I think I've discovered another bug!

**Comment by stramel** [comment]
@samuelli Did this creep back in? I'm not seeing selected properties in the `paper-tabs` docs.

**Comment by samuelli** [comment]
@stramel: perhaps. I'm suspecting #1012 right now.
