### ISSUE TITLE
Show that component should be installed with npm

### ISSUE THREAD

**Issue by lastmjs** [webcomponents/webcomponents.org#979]
I've recently switched from bower to npm for my web component: https://github.com/lastmjs/redux-store-element, and I would like that to reflect on webcomponents.org here: https://www.webcomponents.org/element/lastmjs/redux-store-element

Not sure how to do that.

**Comment by samuelli** [comment]
Follow #531 for updates on this.

**Comment by lastmjs** [comment]
#531 should solve this when it's finished, thanks.
