### ISSUE TITLE
Publishers: join the publishers chat

### ISSUE THREAD

**Issue by samuelli** [webcomponents/webcomponents.org#981]
Hi all,

Moving forward it will be important for us to rally as a community for important conversations such as migrating to NPM. Please follow issue #531 for updates on that front.

I'd like to suggest all publishers join the [gitter channel for publishers](https://gitter.im/webcomponents/publishers) so we can chat there and keep in touch with everyone!

Thanks,
Sam

ccing user names based on what's published on webcomponents.org:

@1000ch @3mp3ri0r @abdonrd @abe90 @acordeonl @adelarosab @afloesch @afonsopacifer @albertofdzm @alejandroledesma @alex-saunders @alternatex @amruthpillai @anandabhi @anasium @andymutton @ankitsorathiya @annsonn @aqovia @aqoviaelements @ardean @arfost @arsnebula @artanis @aruntk @arvinh @astri-isns @auth0-blog @avdaredevil @avgp @bbx-kitchen @bc-bfloyd @bendavis78 @bennypowers @biztek @bjerkins @bkawk @blackjack26 @blinktechsg @bluewatertracks @bobvanluijt @borjagodoy @butterandfly @camargo @captaincodeman @chuckh @ciampo @citydogweb @cloudgz @cloudydirk

**Comment by samuelli** [comment]
@cluttered-components @cmidt-veasna @collaborne @convoo @cordova-elements @dabolus @dakmor @danelyons @daniel-cotton @danielx @dashboardelements @dav04 @david-mulder @deepspacedev @dgt41 @diddledan @dimitardanailov @dimshadowww @dloeda @dyazincahya @easymetahub @eavichay @ebidel @eduardolundgren @eduardosada @educastellano @edwardsharp @egkoppel @ellipticaljs @emilbillberg @ergo @ernysans @exmg @expandjs @filipproch @firebase @fjsc @florianfe @fluorescenthallucinogen @fnndsc @fooloomanzoo @frenchynz @friendsofpolymer @fs-webcomponents @g200kg @gabiaxel @geelen @geoloeg @gerard-payne @gerhardhh

**Comment by samuelli** [comment]
@ginkgobioworks @giovanni0918 @girliemac @github @gjdenhertog @gladcube @globalfreightsolutions @gnurub @google @googlecast @googlewebcomponents @gorork @grafitto @granze @greenhopper @greenyouse @gronke @grumpypufferfish @henrykode @hispar @htmlelement @hyyan @ibmresearch @ichiban @idanen @iftachsadeh @ingressorapidowebcomponents @inrego @ireade @iswpolymerelements @itsmebender @ivanrod @ivanzusko @jaysunsyn @jefflefoll @jgw96 @jifalops @johnnyboyct @johnpryan @jonsmithers @jordanfinners @jordyvandomselaar @jorgecasar @joserochadocarmo @jrtnq514 @jshcrowthe @jstnhuang @juicy @juravenator @justinribeiro

**Comment by samuelli** [comment]
@k4ng @kcmr @kilombo @kkpoon @klarkc @koada-os @laat @larsgk @lasalefamine @lastmjs @leodido @lgaribaldi @link2twenty @littleqairoes @lordoftheflies @lostinbrittany @lrnwebcomponents @lsspolymerelements @lzsoft @macthezazou @majorbreakfast @manohar-gunturu @manufosela @maps4html @marcus7777 @markjameshoward @mathiasbynens @matthewp @mckreukniet @mediamath @meravici @mercmobily @mgibas @michaelfba @midorikocak @miguelsmuller @milesje @mistio @miztroh @mlisook @moebiusmania @motss @mpachnis @mqttjs @mycomosi @myfrom @myscript @naderio @namannehra @neilujd @nevraeka @nicolasrannou @nodecgelements @notwaldorf @nuclei @nuxeo @oi-oy-div @olivierlangelaar @optinomic @oscarmcm @oscarsolas @owox @oyeharry @paolobeltrame @paperfireelements @patriciapds @paulkinlan @paulvarache @pearlbea @petja @pfelements @phenome @photoshelter @pixelscommander @plataformatec @platosha @polymer @polymeraws @polymerel @polymerelements @polymerlabs @polymervis @pomber @printminion @protoss78 @puranjayjain @pwasem @qed42 @rafiuske @raulsntos @rayabhagis @redbility @rediche @regou @reinert @rene-lindner-isw @renfeng @revathskumar @rnicholus @roberttaraya @rogeriopvl @roxus @ruyadorno @ryanburns23 @saeidzebardast @safetychanger @salte-io @samiheikki @samjacobclift @samthecodingman @samthor @samuelli @saneyan @saulis @sbeleidy @sbonnick @scarygami @schemerapp @scramjs @seaneking @seijihirao @sespiros @shah-parth @sharedlabs @shawncplus @shibuielements @simoneas02 @simplaelements @simplaio @simpleelements @sorin-davidoi @sparhami @startpolymer @streetturtle @super-elements @t2ym @tegola @tehapo @telecomsante @the-catalin @thomascybulski @tiki-elements @tim-mehlhorn @timeu @timvdlippe @tomberek @toshovski @tpluscode @trofrigo @tryggvigy @ttretau @tur-nr @txsmith @tzolov @vaadin @valdrinkoshi @vardius @veith @vguillou @vhr @vic10us @virtuvia @vitantonioc @vogelrh @vpusher @wasc-io @wbinnssmith @wburgers @web-padawan @webcomponents @webcoreelements @webduinoio @webpaperelements @wincinderith @wintersandroid @wmginsberg @woutervroege @xliiv @yaireo @yuanchuan @zacharytamas @zecat @zedesk

**Comment by samuelli** [comment]
@nevraeka @nicolasrannou @nodecgelements @notwaldorf @nuclei @nuxeo @oi-oy-div @olivierlangelaar @optinomic @oscarmcm @oscarsolas @owox @oyeharry @paolobeltrame @paperfireelements @patriciapds @paulkinlan @paulvarache @pearlbea @petja @pfelements @phenome @photoshelter @pixelscommander @plataformatec @platosha @polymer @polymeraws @polymerel @polymerelements @polymerlabs @polymervis @pomber @printminion @protoss78 @puranjayjain @pwasem @qed42 @rafiuske @raulsntos @rayabhagis @redbility @rediche @regou @reinert @rene-lindner-isw @renfeng @revathskumar @rnicholus @roberttaraya

**Comment by samuelli** [comment]
@rogeriopvl @roxus @ruyadorno @ryanburns23 @saeidzebardast @safetychanger @salte-io @samiheikki @samjacobclift @samthecodingman @samthor @samuelli @saneyan @saulis @sbeleidy @sbonnick @scarygami @schemerapp @scramjs @seaneking @seijihirao @sespiros @shah-parth @sharedlabs @shawncplus @shibuielements @simoneas02 @simplaelements @simplaio @simpleelements @sorin-davidoi @sparhami @startpolymer @streetturtle @super-elements @t2ym @tegola @tehapo @telecomsante @the-catalin @thomascybulski @tiki-elements @tim-mehlhorn @timeu @timvdlippe @tomberek @toshovski @tpluscode @trofrigo @tryggvigy @ttretau @tur-nr @txsmith @tzolov @vaadin @valdrinkoshi @vardius @veith @vguillou @vhr @vic10us @virtuvia @vitantonioc @vogelrh @vpusher @wasc-io @wbinnssmith @wburgers @web-padawan @webcomponents @webcoreelements @webduinoio @webpaperelements @wincinderith @wintersandroid @wmginsberg @woutervroege @xliiv @yaireo @yuanchuan @zacharytamas @zecat @zedesk

**Comment by samiheikki** [comment]
Thanks @samuelli

**Comment by Dabolus** [comment]
Joined, thank you :)

**Comment by leodido** [comment]
Joined, thanks
