### ISSUE TITLE
404 errors on pages

### ISSUE THREAD

**Issue by Leecase99** [webcomponents/webcomponents.org#985]
[Origin page] On this github page:
https://www.webcomponents.org/element/PolymerElements/iron-icons

There are 3 github page references at the bottom of this page. All links return a 404 error. 
Here they are:
https://github.com/PolymerElements/iron-icons/blob/master/iron-iconset-svg
https://github.com/PolymerElements/iron-icons/blob/master/iron-iconset
https://github.com/PolymerElements/iron-icons/blob/master/iron-icon

Use Case: I am trying to create a small set of SVG icons from the iron-icon set my developers are using to use in elements like User and Developer documentation for reference to the App we are building.  

I was hoping these pages might have more information.  Thanks.

Leecase99

**Comment by samuelli** [comment]
Thanks for the report.

This had already been fixed in the repo, just needed a release. Should be fixed now!
