### ISSUE TITLE
Anchor references don't work

### ISSUE THREAD

**Issue by AlecBenzer** [webcomponents/webcomponents.org#989]
E.g., this link (https://www.webcomponents.org/element/PolymerElements/paper-toggle-button/elements/paper-toggle-button#property-toggles) does not actually scroll down to the referenced property for me (Chrome 59.0.3071.86 (Official Build) (64-bit) on Linux)

**Comment by samuelli** [comment]
This should work with the latest update! Thanks for filing - let me know if you encounter any other issues.
