### ISSUE TITLE
Enable iframe attributes for demos

### ISSUE THREAD

**Issue by jorgecasar** [webcomponents/webcomponents.org#990]
Some APIs like Payment Request to work inside iframes require an attribute. More info: https://github.com/w3c/browser-payment-api/issues/2

The demo of my component jorgecasar/payment-request doesn't work because of that.

**Comment by samuelli** [comment]
What attribute do you need to add?

**Comment by jorgecasar** [comment]
allowpaymentrequest

https://github.com/w3c/browser-payment-api/pull/268

**Comment by samuelli** [comment]
Cross origin iframes are particularly locked down in browsers based on security concerns. I'm worried that this opens this up in unintended ways. eg. essentially there could be a payment request coming from webcomponents.org origin. As such, I'm pretty hesitant to open this up.

I would suggest hosting this demo on its own site and link to that in places. You can specify a full path in the demos field in your bower.json so it still shows up on wc.org but will open in a new tab. It will mean an inline demo won't work in this case. What do you think?

**Comment by jorgecasar** [comment]
Ok, I didn't know that. It will work. Thanks.

**Comment by jorgecasar** [comment]
@samuelli including it in bower I have 2 "Demo" links. I don't want to delete the @demo comment of my component because it will not appear in the `iron-component-page`.

Here is the commit: https://github.com/jorgecasar/payment-request/commit/8e4bcbe2c0207fe27f8efeb1bc1662b0582538bc

And here is the result: https://www.webcomponents.org/preview/jorgecasar/payment-request/8e4bcbe2c0207fe27f8efeb1bc1662b0582538bc

**Comment by samuelli** [comment]
Ouch, that's not good. I'm not sure what can be done, sorry :(
